// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_text.proto
// Protobuf C++ Version: 7.34.0

#include "proto/renderprotocol/ui/v1/rp_ui_text.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace proto {
namespace renderprotocol {
namespace ui {
namespace v1 {

inline constexpr RPTextStyle::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        font_family_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        color_{nullptr},
        font_size_{0},
        font_weight_{static_cast< ::proto::renderprotocol::ui::v1::RPFontWeight >(0)},
        line_height_{0},
        letter_spacing_{0},
        decoration_{static_cast< ::proto::renderprotocol::ui::v1::RPTextDecoration >(0)},
        font_style_{static_cast< ::proto::renderprotocol::ui::v1::RPFontStyle >(0)} {}

template <typename>
constexpr RPTextStyle::RPTextStyle(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RPTextStyle_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct RPTextStyleDefaultTypeInternal {
  constexpr RPTextStyleDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RPTextStyleDefaultTypeInternal() {}
  union {
    RPTextStyle _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RPTextStyleDefaultTypeInternal _RPTextStyle_default_instance_;

inline constexpr RPText::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        style_{nullptr},
        max_lines_{0},
        overflow_{static_cast< ::proto::renderprotocol::ui::v1::RPTextOverflow >(0)},
        text_alignment_{static_cast< ::proto::renderprotocol::ui::v1::RPTextAlignment >(0)} {}

template <typename>
constexpr RPText::RPText(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RPText_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct RPTextDefaultTypeInternal {
  constexpr RPTextDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RPTextDefaultTypeInternal() {}
  union {
    RPText _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RPTextDefaultTypeInternal _RPText_default_instance_;
}  // namespace v1
}  // namespace ui
}  // namespace renderprotocol
}  // namespace proto
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto[5];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto = nullptr;
const ::uint32_t
    TableStruct_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPText, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPText, _impl_.value_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPText, _impl_.style_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPText, _impl_.max_lines_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPText, _impl_.overflow_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPText, _impl_.text_alignment_),
        0,
        1,
        2,
        3,
        4,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPTextStyle, _impl_._has_bits_),
        11, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPTextStyle, _impl_.font_size_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPTextStyle, _impl_.font_weight_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPTextStyle, _impl_.color_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPTextStyle, _impl_.line_height_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPTextStyle, _impl_.letter_spacing_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPTextStyle, _impl_.decoration_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPTextStyle, _impl_.font_family_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPTextStyle, _impl_.font_style_),
        2,
        3,
        1,
        4,
        5,
        6,
        0,
        7,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::proto::renderprotocol::ui::v1::RPText)},
        {13, sizeof(::proto::renderprotocol::ui::v1::RPTextStyle)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::proto::renderprotocol::ui::v1::_RPText_default_instance_._instance,
    &::proto::renderprotocol::ui::v1::_RPTextStyle_default_instance_._instance,
};
const char descriptor_table_protodef_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n+proto/renderprotocol/ui/v1/rp_ui_text."
    "proto\022\032proto.renderprotocol.ui.v1\032,proto"
    "/renderprotocol/ui/v1/rp_ui_color.proto\""
    "\270\002\n\006RPText\022\024\n\005value\030\001 \001(\tR\005value\022B\n\005styl"
    "e\030\002 \001(\0132\'.proto.renderprotocol.ui.v1.RPT"
    "extStyleH\000R\005style\210\001\001\022 \n\tmax_lines\030\003 \001(\005H"
    "\001R\010maxLines\210\001\001\022F\n\010overflow\030\004 \001(\0162*.proto"
    ".renderprotocol.ui.v1.RPTextOverflowR\010ov"
    "erflow\022R\n\016text_alignment\030\005 \001(\0162+.proto.r"
    "enderprotocol.ui.v1.RPTextAlignmentR\rtex"
    "tAlignmentB\010\n\006_styleB\014\n\n_max_lines\"\223\004\n\013R"
    "PTextStyle\022 \n\tfont_size\030\001 \001(\002H\000R\010fontSiz"
    "e\210\001\001\022I\n\013font_weight\030\002 \001(\0162(.proto.render"
    "protocol.ui.v1.RPFontWeightR\nfontWeight\022"
    ">\n\005color\030\003 \001(\0132#.proto.renderprotocol.ui"
    ".v1.RPColorH\001R\005color\210\001\001\022$\n\013line_height\030\004"
    " \001(\002H\002R\nlineHeight\210\001\001\022*\n\016letter_spacing\030"
    "\005 \001(\002H\003R\rletterSpacing\210\001\001\022L\n\ndecoration\030"
    "\006 \001(\0162,.proto.renderprotocol.ui.v1.RPTex"
    "tDecorationR\ndecoration\022$\n\013font_family\030\007"
    " \001(\tH\004R\nfontFamily\210\001\001\022F\n\nfont_style\030\010 \001("
    "\0162\'.proto.renderprotocol.ui.v1.RPFontSty"
    "leR\tfontStyleB\014\n\n_font_sizeB\010\n\006_colorB\016\n"
    "\014_line_heightB\021\n\017_letter_spacingB\016\n\014_fon"
    "t_family*\250\002\n\014RPFontWeight\022\036\n\032RP_FONT_WEI"
    "GHT_UNSPECIFIED\020\000\022\027\n\023RP_FONT_WEIGHT_THIN"
    "\020\001\022\036\n\032RP_FONT_WEIGHT_EXTRA_LIGHT\020\002\022\030\n\024RP"
    "_FONT_WEIGHT_LIGHT\020\003\022\032\n\026RP_FONT_WEIGHT_R"
    "EGULAR\020\004\022\031\n\025RP_FONT_WEIGHT_MEDIUM\020\005\022\034\n\030R"
    "P_FONT_WEIGHT_SEMI_BOLD\020\006\022\027\n\023RP_FONT_WEI"
    "GHT_BOLD\020\007\022\035\n\031RP_FONT_WEIGHT_EXTRA_BOLD\020"
    "\010\022\030\n\024RP_FONT_WEIGHT_BLACK\020\t*`\n\013RPFontSty"
    "le\022\035\n\031RP_FONT_STYLE_UNSPECIFIED\020\000\022\030\n\024RP_"
    "FONT_STYLE_NORMAL\020\001\022\030\n\024RP_FONT_STYLE_ITA"
    "LIC\020\002*\273\001\n\020RPTextDecoration\022\"\n\036RP_TEXT_DE"
    "CORATION_UNSPECIFIED\020\000\022\033\n\027RP_TEXT_DECORA"
    "TION_NONE\020\001\022 \n\034RP_TEXT_DECORATION_UNDERL"
    "INE\020\002\022#\n\037RP_TEXT_DECORATION_LINE_THROUGH"
    "\020\003\022\037\n\033RP_TEXT_DECORATION_OVERLINE\020\004*\207\001\n\016"
    "RPTextOverflow\022 \n\034RP_TEXT_OVERFLOW_UNSPE"
    "CIFIED\020\000\022\031\n\025RP_TEXT_OVERFLOW_CLIP\020\001\022\035\n\031R"
    "P_TEXT_OVERFLOW_ELLIPSIS\020\002\022\031\n\025RP_TEXT_OV"
    "ERFLOW_FADE\020\003*\252\001\n\017RPTextAlignment\022!\n\035RP_"
    "TEXT_ALIGNMENT_UNSPECIFIED\020\000\022\032\n\026RP_TEXT_"
    "ALIGNMENT_LEFT\020\001\022\034\n\030RP_TEXT_ALIGNMENT_CE"
    "NTER\020\002\022\033\n\027RP_TEXT_ALIGNMENT_RIGHT\020\003\022\035\n\031R"
    "P_TEXT_ALIGNMENT_JUSTIFY\020\004B\302\001\n\036com.proto"
    ".renderprotocol.ui.v1B\rRpUiTextProtoH\001P\001"
    "\370\001\001\242\002\003PRU\252\002\032Proto.Renderprotocol.Ui.V1\272\002"
    "\000\312\002\032Proto\\Renderprotocol\\Ui\\V1\342\002&Proto\\R"
    "enderprotocol\\Ui\\V1\\GPBMetadata\352\002\035Proto:"
    ":Renderprotocol::Ui::V1b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto_deps[1] = {
        &::descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fcolor_2eproto,
};
static ::absl::once_flag descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto = {
    false,
    false,
    2071,
    descriptor_table_protodef_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto,
    "proto/renderprotocol/ui/v1/rp_ui_text.proto",
    &descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto_once,
    descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto::offsets,
    file_level_enum_descriptors_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto,
    file_level_service_descriptors_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto,
};
namespace proto {
namespace renderprotocol {
namespace ui {
namespace v1 {
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
RPFontWeight_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto);
  return file_level_enum_descriptors_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t RPFontWeight_internal_data_[] = {
    655360u, 0u, };
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
RPFontStyle_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto);
  return file_level_enum_descriptors_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t RPFontStyle_internal_data_[] = {
    196608u, 0u, };
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
RPTextDecoration_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto);
  return file_level_enum_descriptors_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto[2];
}
PROTOBUF_CONSTINIT const uint32_t RPTextDecoration_internal_data_[] = {
    327680u, 0u, };
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
RPTextOverflow_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto);
  return file_level_enum_descriptors_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto[3];
}
PROTOBUF_CONSTINIT const uint32_t RPTextOverflow_internal_data_[] = {
    262144u, 0u, };
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
RPTextAlignment_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto);
  return file_level_enum_descriptors_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto[4];
}
PROTOBUF_CONSTINIT const uint32_t RPTextAlignment_internal_data_[] = {
    327680u, 0u, };
// ===================================================================

class RPText::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RPText>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RPText, _impl_._has_bits_);
};

RPText::RPText(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RPText_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.renderprotocol.ui.v1.RPText)
}
PROTOBUF_NDEBUG_INLINE RPText::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::renderprotocol::ui::v1::RPText& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        value_(arena, from.value_) {}

RPText::RPText(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RPText& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RPText_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RPText* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.style_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.style_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, max_lines_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, max_lines_),
           offsetof(Impl_, text_alignment_) -
               offsetof(Impl_, max_lines_) +
               sizeof(Impl_::text_alignment_));

  // @@protoc_insertion_point(copy_constructor:proto.renderprotocol.ui.v1.RPText)
}
PROTOBUF_NDEBUG_INLINE RPText::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        value_(arena) {}

inline void RPText::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, style_),
           0,
           offsetof(Impl_, text_alignment_) -
               offsetof(Impl_, style_) +
               sizeof(Impl_::text_alignment_));
}
RPText::~RPText() {
  // @@protoc_insertion_point(destructor:proto.renderprotocol.ui.v1.RPText)
  SharedDtor(*this);
}
inline void RPText::SharedDtor(MessageLite& self) {
  RPText& this_ = static_cast<RPText&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.value_.Destroy();
  delete this_._impl_.style_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RPText::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RPText(arena);
}
constexpr auto RPText::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RPText),
                                            alignof(RPText));
}
constexpr auto RPText::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RPText_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &RPText::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RPText>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RPText::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RPText>(), &RPText::ByteSizeLong,
              &RPText::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RPText, _impl_._cached_size_),
          false,
      },
      &RPText::kDescriptorMethods,
      &descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RPText_class_data_ =
        RPText::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RPText::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RPText_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RPText_class_data_.tc_table);
  return RPText_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 1, 47, 2>
RPText::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RPText, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    RPText_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::renderprotocol::ui::v1::RPText>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string value = 1 [json_name = "value"];
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(RPText, _impl_.value_)}},
    // optional .proto.renderprotocol.ui.v1.RPTextStyle style = 2 [json_name = "style"];
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(RPText, _impl_.style_)}},
    // optional int32 max_lines = 3 [json_name = "maxLines"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RPText, _impl_.max_lines_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(RPText, _impl_.max_lines_)}},
    // .proto.renderprotocol.ui.v1.RPTextOverflow overflow = 4 [json_name = "overflow"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RPText, _impl_.overflow_), 3>(),
     {32, 3, 0,
      PROTOBUF_FIELD_OFFSET(RPText, _impl_.overflow_)}},
    // .proto.renderprotocol.ui.v1.RPTextAlignment text_alignment = 5 [json_name = "textAlignment"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RPText, _impl_.text_alignment_), 4>(),
     {40, 4, 0,
      PROTOBUF_FIELD_OFFSET(RPText, _impl_.text_alignment_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string value = 1 [json_name = "value"];
    {PROTOBUF_FIELD_OFFSET(RPText, _impl_.value_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional .proto.renderprotocol.ui.v1.RPTextStyle style = 2 [json_name = "style"];
    {PROTOBUF_FIELD_OFFSET(RPText, _impl_.style_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional int32 max_lines = 3 [json_name = "maxLines"];
    {PROTOBUF_FIELD_OFFSET(RPText, _impl_.max_lines_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // .proto.renderprotocol.ui.v1.RPTextOverflow overflow = 4 [json_name = "overflow"];
    {PROTOBUF_FIELD_OFFSET(RPText, _impl_.overflow_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // .proto.renderprotocol.ui.v1.RPTextAlignment text_alignment = 5 [json_name = "textAlignment"];
    {PROTOBUF_FIELD_OFFSET(RPText, _impl_.text_alignment_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::proto::renderprotocol::ui::v1::RPTextStyle>()},
  }},
  {{
    "\41\5\0\0\0\0\0\0"
    "proto.renderprotocol.ui.v1.RPText"
    "value"
  }},
};
PROTOBUF_NOINLINE void RPText::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.renderprotocol.ui.v1.RPText)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.value_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.style_ != nullptr);
      _impl_.style_->Clear();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000001cU)) {
    ::memset(&_impl_.max_lines_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.text_alignment_) -
        reinterpret_cast<char*>(&_impl_.max_lines_)) + sizeof(_impl_.text_alignment_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RPText::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RPText& this_ = static_cast<const RPText&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RPText::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RPText& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.renderprotocol.ui.v1.RPText)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string value = 1 [json_name = "value"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_value().empty()) {
      const ::std::string& _s = this_._internal_value();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.renderprotocol.ui.v1.RPText.value");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // optional .proto.renderprotocol.ui.v1.RPTextStyle style = 2 [json_name = "style"];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.style_, this_._impl_.style_->GetCachedSize(), target,
        stream);
  }

  // optional int32 max_lines = 3 [json_name = "maxLines"];
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
            stream, this_._internal_max_lines(), target);
  }

  // .proto.renderprotocol.ui.v1.RPTextOverflow overflow = 4 [json_name = "overflow"];
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_overflow() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          4, this_._internal_overflow(), target);
    }
  }

  // .proto.renderprotocol.ui.v1.RPTextAlignment text_alignment = 5 [json_name = "textAlignment"];
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_text_alignment() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          5, this_._internal_text_alignment(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.renderprotocol.ui.v1.RPText)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RPText::ByteSizeLong(const MessageLite& base) {
  const RPText& this_ = static_cast<const RPText&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RPText::ByteSizeLong() const {
  const RPText& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.renderprotocol.ui.v1.RPText)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // string value = 1 [json_name = "value"];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_value().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_value());
      }
    }
    // optional .proto.renderprotocol.ui.v1.RPTextStyle style = 2 [json_name = "style"];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.style_);
    }
    // optional int32 max_lines = 3 [json_name = "maxLines"];
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_max_lines());
    }
    // .proto.renderprotocol.ui.v1.RPTextOverflow overflow = 4 [json_name = "overflow"];
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_overflow() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_overflow());
      }
    }
    // .proto.renderprotocol.ui.v1.RPTextAlignment text_alignment = 5 [json_name = "textAlignment"];
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_text_alignment() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_text_alignment());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RPText::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<RPText*>(&to_msg);
  auto& from = static_cast<const RPText&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.renderprotocol.ui.v1.RPText)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_value().empty()) {
        _this->_internal_set_value(from._internal_value());
      } else {
        if (_this->_impl_.value_.IsDefault()) {
          _this->_internal_set_value("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.style_ != nullptr);
      if (_this->_impl_.style_ == nullptr) {
        _this->_impl_.style_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.style_);
      } else {
        _this->_impl_.style_->MergeFrom(*from._impl_.style_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.max_lines_ = from._impl_.max_lines_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_overflow() != 0) {
        _this->_impl_.overflow_ = from._impl_.overflow_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_text_alignment() != 0) {
        _this->_impl_.text_alignment_ = from._impl_.text_alignment_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void RPText::CopyFrom(const RPText& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.renderprotocol.ui.v1.RPText)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RPText::InternalSwap(RPText* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RPText, _impl_.text_alignment_)
      + sizeof(RPText::_impl_.text_alignment_)
      - PROTOBUF_FIELD_OFFSET(RPText, _impl_.style_)>(
          reinterpret_cast<char*>(&_impl_.style_),
          reinterpret_cast<char*>(&other->_impl_.style_));
}

::google::protobuf::Metadata RPText::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RPTextStyle::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RPTextStyle>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RPTextStyle, _impl_._has_bits_);
};

void RPTextStyle::clear_color() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.color_ != nullptr) _impl_.color_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
RPTextStyle::RPTextStyle(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RPTextStyle_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.renderprotocol.ui.v1.RPTextStyle)
}
PROTOBUF_NDEBUG_INLINE RPTextStyle::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::renderprotocol::ui::v1::RPTextStyle& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        font_family_(arena, from.font_family_) {}

RPTextStyle::RPTextStyle(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RPTextStyle& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RPTextStyle_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RPTextStyle* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.color_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.color_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, font_size_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, font_size_),
           offsetof(Impl_, font_style_) -
               offsetof(Impl_, font_size_) +
               sizeof(Impl_::font_style_));

  // @@protoc_insertion_point(copy_constructor:proto.renderprotocol.ui.v1.RPTextStyle)
}
PROTOBUF_NDEBUG_INLINE RPTextStyle::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        font_family_(arena) {}

inline void RPTextStyle::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, color_),
           0,
           offsetof(Impl_, font_style_) -
               offsetof(Impl_, color_) +
               sizeof(Impl_::font_style_));
}
RPTextStyle::~RPTextStyle() {
  // @@protoc_insertion_point(destructor:proto.renderprotocol.ui.v1.RPTextStyle)
  SharedDtor(*this);
}
inline void RPTextStyle::SharedDtor(MessageLite& self) {
  RPTextStyle& this_ = static_cast<RPTextStyle&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.font_family_.Destroy();
  delete this_._impl_.color_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RPTextStyle::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RPTextStyle(arena);
}
constexpr auto RPTextStyle::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RPTextStyle),
                                            alignof(RPTextStyle));
}
constexpr auto RPTextStyle::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RPTextStyle_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &RPTextStyle::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RPTextStyle>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RPTextStyle::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RPTextStyle>(), &RPTextStyle::ByteSizeLong,
              &RPTextStyle::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RPTextStyle, _impl_._cached_size_),
          false,
      },
      &RPTextStyle::kDescriptorMethods,
      &descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RPTextStyle_class_data_ =
        RPTextStyle::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RPTextStyle::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RPTextStyle_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RPTextStyle_class_data_.tc_table);
  return RPTextStyle_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 8, 1, 66, 2>
RPTextStyle::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RPTextStyle, _impl_._has_bits_),
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967040,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    RPTextStyle_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::renderprotocol::ui::v1::RPTextStyle>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .proto.renderprotocol.ui.v1.RPFontStyle font_style = 8 [json_name = "fontStyle"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RPTextStyle, _impl_.font_style_), 7>(),
     {64, 7, 0,
      PROTOBUF_FIELD_OFFSET(RPTextStyle, _impl_.font_style_)}},
    // optional float font_size = 1 [json_name = "fontSize"];
    {::_pbi::TcParser::FastF32S1,
     {13, 2, 0,
      PROTOBUF_FIELD_OFFSET(RPTextStyle, _impl_.font_size_)}},
    // .proto.renderprotocol.ui.v1.RPFontWeight font_weight = 2 [json_name = "fontWeight"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RPTextStyle, _impl_.font_weight_), 3>(),
     {16, 3, 0,
      PROTOBUF_FIELD_OFFSET(RPTextStyle, _impl_.font_weight_)}},
    // optional .proto.renderprotocol.ui.v1.RPColor color = 3 [json_name = "color"];
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(RPTextStyle, _impl_.color_)}},
    // optional float line_height = 4 [json_name = "lineHeight"];
    {::_pbi::TcParser::FastF32S1,
     {37, 4, 0,
      PROTOBUF_FIELD_OFFSET(RPTextStyle, _impl_.line_height_)}},
    // optional float letter_spacing = 5 [json_name = "letterSpacing"];
    {::_pbi::TcParser::FastF32S1,
     {45, 5, 0,
      PROTOBUF_FIELD_OFFSET(RPTextStyle, _impl_.letter_spacing_)}},
    // .proto.renderprotocol.ui.v1.RPTextDecoration decoration = 6 [json_name = "decoration"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RPTextStyle, _impl_.decoration_), 6>(),
     {48, 6, 0,
      PROTOBUF_FIELD_OFFSET(RPTextStyle, _impl_.decoration_)}},
    // optional string font_family = 7 [json_name = "fontFamily"];
    {::_pbi::TcParser::FastUS1,
     {58, 0, 0,
      PROTOBUF_FIELD_OFFSET(RPTextStyle, _impl_.font_family_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional float font_size = 1 [json_name = "fontSize"];
    {PROTOBUF_FIELD_OFFSET(RPTextStyle, _impl_.font_size_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // .proto.renderprotocol.ui.v1.RPFontWeight font_weight = 2 [json_name = "fontWeight"];
    {PROTOBUF_FIELD_OFFSET(RPTextStyle, _impl_.font_weight_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // optional .proto.renderprotocol.ui.v1.RPColor color = 3 [json_name = "color"];
    {PROTOBUF_FIELD_OFFSET(RPTextStyle, _impl_.color_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional float line_height = 4 [json_name = "lineHeight"];
    {PROTOBUF_FIELD_OFFSET(RPTextStyle, _impl_.line_height_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float letter_spacing = 5 [json_name = "letterSpacing"];
    {PROTOBUF_FIELD_OFFSET(RPTextStyle, _impl_.letter_spacing_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // .proto.renderprotocol.ui.v1.RPTextDecoration decoration = 6 [json_name = "decoration"];
    {PROTOBUF_FIELD_OFFSET(RPTextStyle, _impl_.decoration_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // optional string font_family = 7 [json_name = "fontFamily"];
    {PROTOBUF_FIELD_OFFSET(RPTextStyle, _impl_.font_family_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .proto.renderprotocol.ui.v1.RPFontStyle font_style = 8 [json_name = "fontStyle"];
    {PROTOBUF_FIELD_OFFSET(RPTextStyle, _impl_.font_style_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::proto::renderprotocol::ui::v1::RPColor>()},
  }},
  {{
    "\46\0\0\0\0\0\0\13\0\0\0\0\0\0\0\0"
    "proto.renderprotocol.ui.v1.RPTextStyle"
    "font_family"
  }},
};
PROTOBUF_NOINLINE void RPTextStyle::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.renderprotocol.ui.v1.RPTextStyle)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.font_family_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.color_ != nullptr);
      _impl_.color_->Clear();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000000fcU)) {
    ::memset(&_impl_.font_size_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.font_style_) -
        reinterpret_cast<char*>(&_impl_.font_size_)) + sizeof(_impl_.font_style_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RPTextStyle::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RPTextStyle& this_ = static_cast<const RPTextStyle&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RPTextStyle::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RPTextStyle& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.renderprotocol.ui.v1.RPTextStyle)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional float font_size = 1 [json_name = "fontSize"];
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        1, this_._internal_font_size(), target);
  }

  // .proto.renderprotocol.ui.v1.RPFontWeight font_weight = 2 [json_name = "fontWeight"];
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_font_weight() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          2, this_._internal_font_weight(), target);
    }
  }

  // optional .proto.renderprotocol.ui.v1.RPColor color = 3 [json_name = "color"];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.color_, this_._impl_.color_->GetCachedSize(), target,
        stream);
  }

  // optional float line_height = 4 [json_name = "lineHeight"];
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        4, this_._internal_line_height(), target);
  }

  // optional float letter_spacing = 5 [json_name = "letterSpacing"];
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        5, this_._internal_letter_spacing(), target);
  }

  // .proto.renderprotocol.ui.v1.RPTextDecoration decoration = 6 [json_name = "decoration"];
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (this_._internal_decoration() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          6, this_._internal_decoration(), target);
    }
  }

  // optional string font_family = 7 [json_name = "fontFamily"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_font_family();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.renderprotocol.ui.v1.RPTextStyle.font_family");
    target = stream->WriteStringMaybeAliased(7, _s, target);
  }

  // .proto.renderprotocol.ui.v1.RPFontStyle font_style = 8 [json_name = "fontStyle"];
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    if (this_._internal_font_style() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          8, this_._internal_font_style(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.renderprotocol.ui.v1.RPTextStyle)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RPTextStyle::ByteSizeLong(const MessageLite& base) {
  const RPTextStyle& this_ = static_cast<const RPTextStyle&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RPTextStyle::ByteSizeLong() const {
  const RPTextStyle& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.renderprotocol.ui.v1.RPTextStyle)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += ::absl::popcount(0x00000034U & cached_has_bits) * 5;
  if (BatchCheckHasBit(cached_has_bits, 0x000000cbU)) {
    // optional string font_family = 7 [json_name = "fontFamily"];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_font_family());
    }
    // optional .proto.renderprotocol.ui.v1.RPColor color = 3 [json_name = "color"];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.color_);
    }
    // .proto.renderprotocol.ui.v1.RPFontWeight font_weight = 2 [json_name = "fontWeight"];
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_font_weight() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_font_weight());
      }
    }
    // .proto.renderprotocol.ui.v1.RPTextDecoration decoration = 6 [json_name = "decoration"];
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (this_._internal_decoration() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_decoration());
      }
    }
    // .proto.renderprotocol.ui.v1.RPFontStyle font_style = 8 [json_name = "fontStyle"];
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (this_._internal_font_style() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_font_style());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RPTextStyle::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<RPTextStyle*>(&to_msg);
  auto& from = static_cast<const RPTextStyle&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.renderprotocol.ui.v1.RPTextStyle)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_font_family(from._internal_font_family());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.color_ != nullptr);
      if (_this->_impl_.color_ == nullptr) {
        _this->_impl_.color_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.color_);
      } else {
        _this->_impl_.color_->MergeFrom(*from._impl_.color_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.font_size_ = from._impl_.font_size_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_font_weight() != 0) {
        _this->_impl_.font_weight_ = from._impl_.font_weight_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.line_height_ = from._impl_.line_height_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _this->_impl_.letter_spacing_ = from._impl_.letter_spacing_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (from._internal_decoration() != 0) {
        _this->_impl_.decoration_ = from._impl_.decoration_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (from._internal_font_style() != 0) {
        _this->_impl_.font_style_ = from._impl_.font_style_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void RPTextStyle::CopyFrom(const RPTextStyle& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.renderprotocol.ui.v1.RPTextStyle)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RPTextStyle::InternalSwap(RPTextStyle* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.font_family_, &other->_impl_.font_family_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RPTextStyle, _impl_.font_style_)
      + sizeof(RPTextStyle::_impl_.font_style_)
      - PROTOBUF_FIELD_OFFSET(RPTextStyle, _impl_.color_)>(
          reinterpret_cast<char*>(&_impl_.color_),
          reinterpret_cast<char*>(&other->_impl_.color_));
}

::google::protobuf::Metadata RPTextStyle::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace ui
}  // namespace renderprotocol
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
