// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_bottom_nav_bar.proto
// Protobuf C++ Version: 6.33.5

#ifndef proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fbottom_5fnav_5fbar_2eproto_2epb_2eh
#define proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fbottom_5fnav_5fbar_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "proto/renderprotocol/ui/v1/rp_ui_action.pb.h"
#include "proto/renderprotocol/ui/v1/rp_ui_color.pb.h"
#include "proto/renderprotocol/ui/v1/rp_ui_icon.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fbottom_5fnav_5fbar_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fbottom_5fnav_5fbar_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fbottom_5fnav_5fbar_2eproto;
}  // extern "C"
namespace proto {
namespace renderprotocol {
namespace ui {
namespace v1 {
class RPBottomNavBar;
struct RPBottomNavBarDefaultTypeInternal;
extern RPBottomNavBarDefaultTypeInternal _RPBottomNavBar_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RPBottomNavBar_class_data_;
class RPBottomNavItem;
struct RPBottomNavItemDefaultTypeInternal;
extern RPBottomNavItemDefaultTypeInternal _RPBottomNavItem_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RPBottomNavItem_class_data_;
}  // namespace v1
}  // namespace ui
}  // namespace renderprotocol
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace proto {
namespace renderprotocol {
namespace ui {
namespace v1 {

// ===================================================================


// -------------------------------------------------------------------

class RPBottomNavItem final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.renderprotocol.ui.v1.RPBottomNavItem) */ {
 public:
  inline RPBottomNavItem() : RPBottomNavItem(nullptr) {}
  ~RPBottomNavItem() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RPBottomNavItem* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RPBottomNavItem));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RPBottomNavItem(::google::protobuf::internal::ConstantInitialized);

  inline RPBottomNavItem(const RPBottomNavItem& from) : RPBottomNavItem(nullptr, from) {}
  inline RPBottomNavItem(RPBottomNavItem&& from) noexcept
      : RPBottomNavItem(nullptr, ::std::move(from)) {}
  inline RPBottomNavItem& operator=(const RPBottomNavItem& from) {
    CopyFrom(from);
    return *this;
  }
  inline RPBottomNavItem& operator=(RPBottomNavItem&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RPBottomNavItem& default_instance() {
    return *reinterpret_cast<const RPBottomNavItem*>(
        &_RPBottomNavItem_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(RPBottomNavItem& a, RPBottomNavItem& b) { a.Swap(&b); }
  inline void Swap(RPBottomNavItem* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RPBottomNavItem* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RPBottomNavItem* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RPBottomNavItem>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RPBottomNavItem& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RPBottomNavItem& from) { RPBottomNavItem::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RPBottomNavItem* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.renderprotocol.ui.v1.RPBottomNavItem"; }

  explicit RPBottomNavItem(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RPBottomNavItem(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RPBottomNavItem& from);
  RPBottomNavItem(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RPBottomNavItem&& from) noexcept
      : RPBottomNavItem(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLabelFieldNumber = 2,
    kIconFieldNumber = 1,
    kActionFieldNumber = 3,
  };
  // optional string label = 2 [json_name = "label"];
  bool has_label() const;
  void clear_label() ;
  const ::std::string& label() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_label(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_label();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_label();
  void set_allocated_label(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_label() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_label(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_label();

  public:
  // .proto.renderprotocol.ui.v1.RPIcon icon = 1 [json_name = "icon"];
  bool has_icon() const;
  void clear_icon() ;
  const ::proto::renderprotocol::ui::v1::RPIcon& icon() const;
  [[nodiscard]] ::proto::renderprotocol::ui::v1::RPIcon* PROTOBUF_NULLABLE release_icon();
  ::proto::renderprotocol::ui::v1::RPIcon* PROTOBUF_NONNULL mutable_icon();
  void set_allocated_icon(::proto::renderprotocol::ui::v1::RPIcon* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_icon(::proto::renderprotocol::ui::v1::RPIcon* PROTOBUF_NULLABLE value);
  ::proto::renderprotocol::ui::v1::RPIcon* PROTOBUF_NULLABLE unsafe_arena_release_icon();

  private:
  const ::proto::renderprotocol::ui::v1::RPIcon& _internal_icon() const;
  ::proto::renderprotocol::ui::v1::RPIcon* PROTOBUF_NONNULL _internal_mutable_icon();

  public:
  // .proto.renderprotocol.ui.v1.RPAction action = 3 [json_name = "action"];
  bool has_action() const;
  void clear_action() ;
  const ::proto::renderprotocol::ui::v1::RPAction& action() const;
  [[nodiscard]] ::proto::renderprotocol::ui::v1::RPAction* PROTOBUF_NULLABLE release_action();
  ::proto::renderprotocol::ui::v1::RPAction* PROTOBUF_NONNULL mutable_action();
  void set_allocated_action(::proto::renderprotocol::ui::v1::RPAction* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_action(::proto::renderprotocol::ui::v1::RPAction* PROTOBUF_NULLABLE value);
  ::proto::renderprotocol::ui::v1::RPAction* PROTOBUF_NULLABLE unsafe_arena_release_action();

  private:
  const ::proto::renderprotocol::ui::v1::RPAction& _internal_action() const;
  ::proto::renderprotocol::ui::v1::RPAction* PROTOBUF_NONNULL _internal_mutable_action();

  public:
  // @@protoc_insertion_point(class_scope:proto.renderprotocol.ui.v1.RPBottomNavItem)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   2, 56,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RPBottomNavItem& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr label_;
    ::proto::renderprotocol::ui::v1::RPIcon* PROTOBUF_NULLABLE icon_;
    ::proto::renderprotocol::ui::v1::RPAction* PROTOBUF_NULLABLE action_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fbottom_5fnav_5fbar_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RPBottomNavItem_class_data_;
// -------------------------------------------------------------------

class RPBottomNavBar final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.renderprotocol.ui.v1.RPBottomNavBar) */ {
 public:
  inline RPBottomNavBar() : RPBottomNavBar(nullptr) {}
  ~RPBottomNavBar() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RPBottomNavBar* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RPBottomNavBar));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RPBottomNavBar(::google::protobuf::internal::ConstantInitialized);

  inline RPBottomNavBar(const RPBottomNavBar& from) : RPBottomNavBar(nullptr, from) {}
  inline RPBottomNavBar(RPBottomNavBar&& from) noexcept
      : RPBottomNavBar(nullptr, ::std::move(from)) {}
  inline RPBottomNavBar& operator=(const RPBottomNavBar& from) {
    CopyFrom(from);
    return *this;
  }
  inline RPBottomNavBar& operator=(RPBottomNavBar&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RPBottomNavBar& default_instance() {
    return *reinterpret_cast<const RPBottomNavBar*>(
        &_RPBottomNavBar_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(RPBottomNavBar& a, RPBottomNavBar& b) { a.Swap(&b); }
  inline void Swap(RPBottomNavBar* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RPBottomNavBar* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RPBottomNavBar* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RPBottomNavBar>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RPBottomNavBar& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RPBottomNavBar& from) { RPBottomNavBar::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RPBottomNavBar* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.renderprotocol.ui.v1.RPBottomNavBar"; }

  explicit RPBottomNavBar(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RPBottomNavBar(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RPBottomNavBar& from);
  RPBottomNavBar(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RPBottomNavBar&& from) noexcept
      : RPBottomNavBar(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kItemsFieldNumber = 1,
    kBackgroundColorFieldNumber = 3,
    kSelectedColorFieldNumber = 4,
    kUnselectedColorFieldNumber = 5,
    kSelectedIndexFieldNumber = 2,
  };
  // repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];
  int items_size() const;
  private:
  int _internal_items_size() const;

  public:
  void clear_items() ;
  ::proto::renderprotocol::ui::v1::RPBottomNavItem* PROTOBUF_NONNULL mutable_items(int index);
  ::google::protobuf::RepeatedPtrField<::proto::renderprotocol::ui::v1::RPBottomNavItem>* PROTOBUF_NONNULL mutable_items();

  private:
  const ::google::protobuf::RepeatedPtrField<::proto::renderprotocol::ui::v1::RPBottomNavItem>& _internal_items() const;
  ::google::protobuf::RepeatedPtrField<::proto::renderprotocol::ui::v1::RPBottomNavItem>* PROTOBUF_NONNULL _internal_mutable_items();
  public:
  const ::proto::renderprotocol::ui::v1::RPBottomNavItem& items(int index) const;
  ::proto::renderprotocol::ui::v1::RPBottomNavItem* PROTOBUF_NONNULL add_items();
  const ::google::protobuf::RepeatedPtrField<::proto::renderprotocol::ui::v1::RPBottomNavItem>& items() const;
  // optional .proto.renderprotocol.ui.v1.RPColor background_color = 3 [json_name = "backgroundColor"];
  bool has_background_color() const;
  void clear_background_color() ;
  const ::proto::renderprotocol::ui::v1::RPColor& background_color() const;
  [[nodiscard]] ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE release_background_color();
  ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NONNULL mutable_background_color();
  void set_allocated_background_color(::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_background_color(::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE value);
  ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE unsafe_arena_release_background_color();

  private:
  const ::proto::renderprotocol::ui::v1::RPColor& _internal_background_color() const;
  ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NONNULL _internal_mutable_background_color();

  public:
  // optional .proto.renderprotocol.ui.v1.RPColor selected_color = 4 [json_name = "selectedColor"];
  bool has_selected_color() const;
  void clear_selected_color() ;
  const ::proto::renderprotocol::ui::v1::RPColor& selected_color() const;
  [[nodiscard]] ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE release_selected_color();
  ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NONNULL mutable_selected_color();
  void set_allocated_selected_color(::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_selected_color(::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE value);
  ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE unsafe_arena_release_selected_color();

  private:
  const ::proto::renderprotocol::ui::v1::RPColor& _internal_selected_color() const;
  ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NONNULL _internal_mutable_selected_color();

  public:
  // optional .proto.renderprotocol.ui.v1.RPColor unselected_color = 5 [json_name = "unselectedColor"];
  bool has_unselected_color() const;
  void clear_unselected_color() ;
  const ::proto::renderprotocol::ui::v1::RPColor& unselected_color() const;
  [[nodiscard]] ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE release_unselected_color();
  ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NONNULL mutable_unselected_color();
  void set_allocated_unselected_color(::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_unselected_color(::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE value);
  ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE unsafe_arena_release_unselected_color();

  private:
  const ::proto::renderprotocol::ui::v1::RPColor& _internal_unselected_color() const;
  ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NONNULL _internal_mutable_unselected_color();

  public:
  // optional int32 selected_index = 2 [json_name = "selectedIndex"];
  bool has_selected_index() const;
  void clear_selected_index() ;
  ::int32_t selected_index() const;
  void set_selected_index(::int32_t value);

  private:
  ::int32_t _internal_selected_index() const;
  void _internal_set_selected_index(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:proto.renderprotocol.ui.v1.RPBottomNavBar)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   4, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RPBottomNavBar& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::proto::renderprotocol::ui::v1::RPBottomNavItem > items_;
    ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE background_color_;
    ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE selected_color_;
    ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE unselected_color_;
    ::int32_t selected_index_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fbottom_5fnav_5fbar_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RPBottomNavBar_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RPBottomNavBar

// repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];
inline int RPBottomNavBar::_internal_items_size() const {
  return _internal_items().size();
}
inline int RPBottomNavBar::items_size() const {
  return _internal_items_size();
}
inline void RPBottomNavBar::clear_items() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.items_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::proto::renderprotocol::ui::v1::RPBottomNavItem* PROTOBUF_NONNULL RPBottomNavBar::mutable_items(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:proto.renderprotocol.ui.v1.RPBottomNavBar.items)
  return _internal_mutable_items()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::proto::renderprotocol::ui::v1::RPBottomNavItem>* PROTOBUF_NONNULL RPBottomNavBar::mutable_items()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:proto.renderprotocol.ui.v1.RPBottomNavBar.items)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_items();
}
inline const ::proto::renderprotocol::ui::v1::RPBottomNavItem& RPBottomNavBar::items(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.ui.v1.RPBottomNavBar.items)
  return _internal_items().Get(index);
}
inline ::proto::renderprotocol::ui::v1::RPBottomNavItem* PROTOBUF_NONNULL RPBottomNavBar::add_items()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::proto::renderprotocol::ui::v1::RPBottomNavItem* _add =
      _internal_mutable_items()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:proto.renderprotocol.ui.v1.RPBottomNavBar.items)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::proto::renderprotocol::ui::v1::RPBottomNavItem>& RPBottomNavBar::items() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:proto.renderprotocol.ui.v1.RPBottomNavBar.items)
  return _internal_items();
}
inline const ::google::protobuf::RepeatedPtrField<::proto::renderprotocol::ui::v1::RPBottomNavItem>&
RPBottomNavBar::_internal_items() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.items_;
}
inline ::google::protobuf::RepeatedPtrField<::proto::renderprotocol::ui::v1::RPBottomNavItem>* PROTOBUF_NONNULL
RPBottomNavBar::_internal_mutable_items() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.items_;
}

// optional int32 selected_index = 2 [json_name = "selectedIndex"];
inline bool RPBottomNavBar::has_selected_index() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void RPBottomNavBar::clear_selected_index() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.selected_index_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::int32_t RPBottomNavBar::selected_index() const {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.ui.v1.RPBottomNavBar.selected_index)
  return _internal_selected_index();
}
inline void RPBottomNavBar::set_selected_index(::int32_t value) {
  _internal_set_selected_index(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:proto.renderprotocol.ui.v1.RPBottomNavBar.selected_index)
}
inline ::int32_t RPBottomNavBar::_internal_selected_index() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.selected_index_;
}
inline void RPBottomNavBar::_internal_set_selected_index(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.selected_index_ = value;
}

// optional .proto.renderprotocol.ui.v1.RPColor background_color = 3 [json_name = "backgroundColor"];
inline bool RPBottomNavBar::has_background_color() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.background_color_ != nullptr);
  return value;
}
inline const ::proto::renderprotocol::ui::v1::RPColor& RPBottomNavBar::_internal_background_color() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::proto::renderprotocol::ui::v1::RPColor* p = _impl_.background_color_;
  return p != nullptr ? *p : reinterpret_cast<const ::proto::renderprotocol::ui::v1::RPColor&>(::proto::renderprotocol::ui::v1::_RPColor_default_instance_);
}
inline const ::proto::renderprotocol::ui::v1::RPColor& RPBottomNavBar::background_color() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.ui.v1.RPBottomNavBar.background_color)
  return _internal_background_color();
}
inline void RPBottomNavBar::unsafe_arena_set_allocated_background_color(
    ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.background_color_);
  }
  _impl_.background_color_ = reinterpret_cast<::proto::renderprotocol::ui::v1::RPColor*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.renderprotocol.ui.v1.RPBottomNavBar.background_color)
}
inline ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE RPBottomNavBar::release_background_color() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::renderprotocol::ui::v1::RPColor* released = _impl_.background_color_;
  _impl_.background_color_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE RPBottomNavBar::unsafe_arena_release_background_color() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.renderprotocol.ui.v1.RPBottomNavBar.background_color)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::renderprotocol::ui::v1::RPColor* temp = _impl_.background_color_;
  _impl_.background_color_ = nullptr;
  return temp;
}
inline ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NONNULL RPBottomNavBar::_internal_mutable_background_color() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.background_color_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::proto::renderprotocol::ui::v1::RPColor>(GetArena());
    _impl_.background_color_ = reinterpret_cast<::proto::renderprotocol::ui::v1::RPColor*>(p);
  }
  return _impl_.background_color_;
}
inline ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NONNULL RPBottomNavBar::mutable_background_color()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::renderprotocol::ui::v1::RPColor* _msg = _internal_mutable_background_color();
  // @@protoc_insertion_point(field_mutable:proto.renderprotocol.ui.v1.RPBottomNavBar.background_color)
  return _msg;
}
inline void RPBottomNavBar::set_allocated_background_color(::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.background_color_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.background_color_ = reinterpret_cast<::proto::renderprotocol::ui::v1::RPColor*>(value);
  // @@protoc_insertion_point(field_set_allocated:proto.renderprotocol.ui.v1.RPBottomNavBar.background_color)
}

// optional .proto.renderprotocol.ui.v1.RPColor selected_color = 4 [json_name = "selectedColor"];
inline bool RPBottomNavBar::has_selected_color() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  PROTOBUF_ASSUME(!value || _impl_.selected_color_ != nullptr);
  return value;
}
inline const ::proto::renderprotocol::ui::v1::RPColor& RPBottomNavBar::_internal_selected_color() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::proto::renderprotocol::ui::v1::RPColor* p = _impl_.selected_color_;
  return p != nullptr ? *p : reinterpret_cast<const ::proto::renderprotocol::ui::v1::RPColor&>(::proto::renderprotocol::ui::v1::_RPColor_default_instance_);
}
inline const ::proto::renderprotocol::ui::v1::RPColor& RPBottomNavBar::selected_color() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.ui.v1.RPBottomNavBar.selected_color)
  return _internal_selected_color();
}
inline void RPBottomNavBar::unsafe_arena_set_allocated_selected_color(
    ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.selected_color_);
  }
  _impl_.selected_color_ = reinterpret_cast<::proto::renderprotocol::ui::v1::RPColor*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.renderprotocol.ui.v1.RPBottomNavBar.selected_color)
}
inline ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE RPBottomNavBar::release_selected_color() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::proto::renderprotocol::ui::v1::RPColor* released = _impl_.selected_color_;
  _impl_.selected_color_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE RPBottomNavBar::unsafe_arena_release_selected_color() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.renderprotocol.ui.v1.RPBottomNavBar.selected_color)

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::proto::renderprotocol::ui::v1::RPColor* temp = _impl_.selected_color_;
  _impl_.selected_color_ = nullptr;
  return temp;
}
inline ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NONNULL RPBottomNavBar::_internal_mutable_selected_color() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.selected_color_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::proto::renderprotocol::ui::v1::RPColor>(GetArena());
    _impl_.selected_color_ = reinterpret_cast<::proto::renderprotocol::ui::v1::RPColor*>(p);
  }
  return _impl_.selected_color_;
}
inline ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NONNULL RPBottomNavBar::mutable_selected_color()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::proto::renderprotocol::ui::v1::RPColor* _msg = _internal_mutable_selected_color();
  // @@protoc_insertion_point(field_mutable:proto.renderprotocol.ui.v1.RPBottomNavBar.selected_color)
  return _msg;
}
inline void RPBottomNavBar::set_allocated_selected_color(::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.selected_color_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }

  _impl_.selected_color_ = reinterpret_cast<::proto::renderprotocol::ui::v1::RPColor*>(value);
  // @@protoc_insertion_point(field_set_allocated:proto.renderprotocol.ui.v1.RPBottomNavBar.selected_color)
}

// optional .proto.renderprotocol.ui.v1.RPColor unselected_color = 5 [json_name = "unselectedColor"];
inline bool RPBottomNavBar::has_unselected_color() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  PROTOBUF_ASSUME(!value || _impl_.unselected_color_ != nullptr);
  return value;
}
inline const ::proto::renderprotocol::ui::v1::RPColor& RPBottomNavBar::_internal_unselected_color() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::proto::renderprotocol::ui::v1::RPColor* p = _impl_.unselected_color_;
  return p != nullptr ? *p : reinterpret_cast<const ::proto::renderprotocol::ui::v1::RPColor&>(::proto::renderprotocol::ui::v1::_RPColor_default_instance_);
}
inline const ::proto::renderprotocol::ui::v1::RPColor& RPBottomNavBar::unselected_color() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.ui.v1.RPBottomNavBar.unselected_color)
  return _internal_unselected_color();
}
inline void RPBottomNavBar::unsafe_arena_set_allocated_unselected_color(
    ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.unselected_color_);
  }
  _impl_.unselected_color_ = reinterpret_cast<::proto::renderprotocol::ui::v1::RPColor*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.renderprotocol.ui.v1.RPBottomNavBar.unselected_color)
}
inline ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE RPBottomNavBar::release_unselected_color() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::proto::renderprotocol::ui::v1::RPColor* released = _impl_.unselected_color_;
  _impl_.unselected_color_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE RPBottomNavBar::unsafe_arena_release_unselected_color() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.renderprotocol.ui.v1.RPBottomNavBar.unselected_color)

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::proto::renderprotocol::ui::v1::RPColor* temp = _impl_.unselected_color_;
  _impl_.unselected_color_ = nullptr;
  return temp;
}
inline ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NONNULL RPBottomNavBar::_internal_mutable_unselected_color() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.unselected_color_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::proto::renderprotocol::ui::v1::RPColor>(GetArena());
    _impl_.unselected_color_ = reinterpret_cast<::proto::renderprotocol::ui::v1::RPColor*>(p);
  }
  return _impl_.unselected_color_;
}
inline ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NONNULL RPBottomNavBar::mutable_unselected_color()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::proto::renderprotocol::ui::v1::RPColor* _msg = _internal_mutable_unselected_color();
  // @@protoc_insertion_point(field_mutable:proto.renderprotocol.ui.v1.RPBottomNavBar.unselected_color)
  return _msg;
}
inline void RPBottomNavBar::set_allocated_unselected_color(::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.unselected_color_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }

  _impl_.unselected_color_ = reinterpret_cast<::proto::renderprotocol::ui::v1::RPColor*>(value);
  // @@protoc_insertion_point(field_set_allocated:proto.renderprotocol.ui.v1.RPBottomNavBar.unselected_color)
}

// -------------------------------------------------------------------

// RPBottomNavItem

// .proto.renderprotocol.ui.v1.RPIcon icon = 1 [json_name = "icon"];
inline bool RPBottomNavItem::has_icon() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.icon_ != nullptr);
  return value;
}
inline const ::proto::renderprotocol::ui::v1::RPIcon& RPBottomNavItem::_internal_icon() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::proto::renderprotocol::ui::v1::RPIcon* p = _impl_.icon_;
  return p != nullptr ? *p : reinterpret_cast<const ::proto::renderprotocol::ui::v1::RPIcon&>(::proto::renderprotocol::ui::v1::_RPIcon_default_instance_);
}
inline const ::proto::renderprotocol::ui::v1::RPIcon& RPBottomNavItem::icon() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.ui.v1.RPBottomNavItem.icon)
  return _internal_icon();
}
inline void RPBottomNavItem::unsafe_arena_set_allocated_icon(
    ::proto::renderprotocol::ui::v1::RPIcon* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.icon_);
  }
  _impl_.icon_ = reinterpret_cast<::proto::renderprotocol::ui::v1::RPIcon*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.renderprotocol.ui.v1.RPBottomNavItem.icon)
}
inline ::proto::renderprotocol::ui::v1::RPIcon* PROTOBUF_NULLABLE RPBottomNavItem::release_icon() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::renderprotocol::ui::v1::RPIcon* released = _impl_.icon_;
  _impl_.icon_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::proto::renderprotocol::ui::v1::RPIcon* PROTOBUF_NULLABLE RPBottomNavItem::unsafe_arena_release_icon() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.renderprotocol.ui.v1.RPBottomNavItem.icon)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::renderprotocol::ui::v1::RPIcon* temp = _impl_.icon_;
  _impl_.icon_ = nullptr;
  return temp;
}
inline ::proto::renderprotocol::ui::v1::RPIcon* PROTOBUF_NONNULL RPBottomNavItem::_internal_mutable_icon() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.icon_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::proto::renderprotocol::ui::v1::RPIcon>(GetArena());
    _impl_.icon_ = reinterpret_cast<::proto::renderprotocol::ui::v1::RPIcon*>(p);
  }
  return _impl_.icon_;
}
inline ::proto::renderprotocol::ui::v1::RPIcon* PROTOBUF_NONNULL RPBottomNavItem::mutable_icon()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::renderprotocol::ui::v1::RPIcon* _msg = _internal_mutable_icon();
  // @@protoc_insertion_point(field_mutable:proto.renderprotocol.ui.v1.RPBottomNavItem.icon)
  return _msg;
}
inline void RPBottomNavItem::set_allocated_icon(::proto::renderprotocol::ui::v1::RPIcon* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.icon_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.icon_ = reinterpret_cast<::proto::renderprotocol::ui::v1::RPIcon*>(value);
  // @@protoc_insertion_point(field_set_allocated:proto.renderprotocol.ui.v1.RPBottomNavItem.icon)
}

// optional string label = 2 [json_name = "label"];
inline bool RPBottomNavItem::has_label() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void RPBottomNavItem::clear_label() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.label_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& RPBottomNavItem::label() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.ui.v1.RPBottomNavItem.label)
  return _internal_label();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RPBottomNavItem::set_label(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.label_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:proto.renderprotocol.ui.v1.RPBottomNavItem.label)
}
inline ::std::string* PROTOBUF_NONNULL RPBottomNavItem::mutable_label()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_label();
  // @@protoc_insertion_point(field_mutable:proto.renderprotocol.ui.v1.RPBottomNavItem.label)
  return _s;
}
inline const ::std::string& RPBottomNavItem::_internal_label() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.label_.Get();
}
inline void RPBottomNavItem::_internal_set_label(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.label_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RPBottomNavItem::_internal_mutable_label() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.label_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RPBottomNavItem::release_label() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.renderprotocol.ui.v1.RPBottomNavItem.label)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.label_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.label_.Set("", GetArena());
  }
  return released;
}
inline void RPBottomNavItem::set_allocated_label(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.label_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.label_.IsDefault()) {
    _impl_.label_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.renderprotocol.ui.v1.RPBottomNavItem.label)
}

// .proto.renderprotocol.ui.v1.RPAction action = 3 [json_name = "action"];
inline bool RPBottomNavItem::has_action() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  PROTOBUF_ASSUME(!value || _impl_.action_ != nullptr);
  return value;
}
inline const ::proto::renderprotocol::ui::v1::RPAction& RPBottomNavItem::_internal_action() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::proto::renderprotocol::ui::v1::RPAction* p = _impl_.action_;
  return p != nullptr ? *p : reinterpret_cast<const ::proto::renderprotocol::ui::v1::RPAction&>(::proto::renderprotocol::ui::v1::_RPAction_default_instance_);
}
inline const ::proto::renderprotocol::ui::v1::RPAction& RPBottomNavItem::action() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.ui.v1.RPBottomNavItem.action)
  return _internal_action();
}
inline void RPBottomNavItem::unsafe_arena_set_allocated_action(
    ::proto::renderprotocol::ui::v1::RPAction* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.action_);
  }
  _impl_.action_ = reinterpret_cast<::proto::renderprotocol::ui::v1::RPAction*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.renderprotocol.ui.v1.RPBottomNavItem.action)
}
inline ::proto::renderprotocol::ui::v1::RPAction* PROTOBUF_NULLABLE RPBottomNavItem::release_action() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::proto::renderprotocol::ui::v1::RPAction* released = _impl_.action_;
  _impl_.action_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::proto::renderprotocol::ui::v1::RPAction* PROTOBUF_NULLABLE RPBottomNavItem::unsafe_arena_release_action() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.renderprotocol.ui.v1.RPBottomNavItem.action)

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::proto::renderprotocol::ui::v1::RPAction* temp = _impl_.action_;
  _impl_.action_ = nullptr;
  return temp;
}
inline ::proto::renderprotocol::ui::v1::RPAction* PROTOBUF_NONNULL RPBottomNavItem::_internal_mutable_action() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.action_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::proto::renderprotocol::ui::v1::RPAction>(GetArena());
    _impl_.action_ = reinterpret_cast<::proto::renderprotocol::ui::v1::RPAction*>(p);
  }
  return _impl_.action_;
}
inline ::proto::renderprotocol::ui::v1::RPAction* PROTOBUF_NONNULL RPBottomNavItem::mutable_action()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::proto::renderprotocol::ui::v1::RPAction* _msg = _internal_mutable_action();
  // @@protoc_insertion_point(field_mutable:proto.renderprotocol.ui.v1.RPBottomNavItem.action)
  return _msg;
}
inline void RPBottomNavItem::set_allocated_action(::proto::renderprotocol::ui::v1::RPAction* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.action_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }

  _impl_.action_ = reinterpret_cast<::proto::renderprotocol::ui::v1::RPAction*>(value);
  // @@protoc_insertion_point(field_set_allocated:proto.renderprotocol.ui.v1.RPBottomNavItem.action)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace ui
}  // namespace renderprotocol
}  // namespace proto


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fbottom_5fnav_5fbar_2eproto_2epb_2eh
