// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_slider.proto
// Protobuf C++ Version: 7.35.0

#ifndef proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fslider_2eproto_2epb_2eh
#define proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fslider_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7035000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "proto/renderprotocol/ui/v1/rp_ui_action.pb.h"
#include "proto/renderprotocol/ui/v1/rp_ui_color.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fslider_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fslider_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fslider_2eproto;
}  // extern "C"
namespace proto {
namespace renderprotocol {
namespace ui {
namespace v1 {
class RPSlider;
struct RPSliderGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern RPSliderGlobalsTypeInternal RPSlider_globals_;
extern const ::google::protobuf::internal::ClassDataFull RPSlider_class_data_;
#else
extern const RPSliderGlobalsTypeInternal RPSlider_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
}  // namespace v1
}  // namespace ui
}  // namespace renderprotocol
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace proto {
namespace renderprotocol {
namespace ui {
namespace v1 {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED RPSlider final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.renderprotocol.ui.v1.RPSlider) */ {
 public:
  inline RPSlider() : RPSlider(nullptr) {}
  ~RPSlider() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RPSlider* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RPSlider));
  }
#endif

  template <typename = void>
  explicit constexpr RPSlider(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline RPSlider(const RPSlider& from) : RPSlider(nullptr, from) {}
  inline RPSlider(RPSlider&& from) noexcept : RPSlider(nullptr, ::std::move(from)) {}
  inline RPSlider& operator=(const RPSlider& from) {
    CopyFrom(from);
    return *this;
  }
  inline RPSlider& operator=(RPSlider&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const RPSlider& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<RPSlider>(&RPSlider_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(RPSlider& a, RPSlider& b) { a.Swap(&b); }
  inline void Swap(RPSlider* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RPSlider* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] RPSlider* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RPSlider>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RPSlider& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RPSlider& from) { RPSlider::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RPSlider* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.renderprotocol.ui.v1.RPSlider"; }

  explicit RPSlider(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RPSlider(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RPSlider& from);
  RPSlider(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RPSlider&& from) noexcept
      : RPSlider(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFieldIdFieldNumber = 1,
    kActiveColorFieldNumber = 6,
    kOnChangeFieldNumber = 8,
    kMinValueFieldNumber = 2,
    kMaxValueFieldNumber = 3,
    kInitialValueFieldNumber = 4,
    kStepFieldNumber = 5,
    kEnabledFieldNumber = 7,
  };
  // string field_id = 1 [json_name = "fieldId"];
  void clear_field_id() ;
  [[nodiscard]] const ::std::string& field_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_field_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_field_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_field_id();
  void set_allocated_field_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_field_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_field_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_field_id();

  public:
  // optional .proto.renderprotocol.ui.v1.RPColor active_color = 6 [json_name = "activeColor"];
  [[nodiscard]] bool has_active_color()
      const;
  void clear_active_color() ;
  [[nodiscard]] const ::proto::renderprotocol::ui::v1::RPColor& active_color() const;
  [[nodiscard]] ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE release_active_color();
  ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NONNULL mutable_active_color();
  void set_allocated_active_color(::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_active_color(::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE value);
  ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE unsafe_arena_release_active_color();

  private:
  const ::proto::renderprotocol::ui::v1::RPColor& _internal_active_color() const;
  ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NONNULL _internal_mutable_active_color();

  public:
  // optional .proto.renderprotocol.ui.v1.RPAction on_change = 8 [json_name = "onChange"];
  [[nodiscard]] bool has_on_change()
      const;
  void clear_on_change() ;
  [[nodiscard]] const ::proto::renderprotocol::ui::v1::RPAction& on_change() const;
  [[nodiscard]] ::proto::renderprotocol::ui::v1::RPAction* PROTOBUF_NULLABLE release_on_change();
  ::proto::renderprotocol::ui::v1::RPAction* PROTOBUF_NONNULL mutable_on_change();
  void set_allocated_on_change(::proto::renderprotocol::ui::v1::RPAction* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_on_change(::proto::renderprotocol::ui::v1::RPAction* PROTOBUF_NULLABLE value);
  ::proto::renderprotocol::ui::v1::RPAction* PROTOBUF_NULLABLE unsafe_arena_release_on_change();

  private:
  const ::proto::renderprotocol::ui::v1::RPAction& _internal_on_change() const;
  ::proto::renderprotocol::ui::v1::RPAction* PROTOBUF_NONNULL _internal_mutable_on_change();

  public:
  // float min_value = 2 [json_name = "minValue"];
  void clear_min_value() ;
  [[nodiscard]] float min_value() const;
  void set_min_value(float value);

  private:
  float _internal_min_value() const;
  void _internal_set_min_value(float value);

  public:
  // float max_value = 3 [json_name = "maxValue"];
  void clear_max_value() ;
  [[nodiscard]] float max_value() const;
  void set_max_value(float value);

  private:
  float _internal_max_value() const;
  void _internal_set_max_value(float value);

  public:
  // optional float initial_value = 4 [json_name = "initialValue"];
  [[nodiscard]] bool has_initial_value()
      const;
  void clear_initial_value() ;
  [[nodiscard]] float initial_value() const;
  void set_initial_value(float value);

  private:
  float _internal_initial_value() const;
  void _internal_set_initial_value(float value);

  public:
  // optional float step = 5 [json_name = "step"];
  [[nodiscard]] bool has_step()
      const;
  void clear_step() ;
  [[nodiscard]] float step() const;
  void set_step(float value);

  private:
  float _internal_step() const;
  void _internal_set_step(float value);

  public:
  // bool enabled = 7 [json_name = "enabled"];
  void clear_enabled() ;
  [[nodiscard]] bool enabled() const;
  void set_enabled(bool value);

  private:
  bool _internal_enabled() const;
  void _internal_set_enabled(bool value);

  public:
  // @@protoc_insertion_point(class_scope:proto.renderprotocol.ui.v1.RPSlider)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<3, 8,
                          2, 60,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RPSlider& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr field_id_;
    ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE active_color_;
    ::proto::renderprotocol::ui::v1::RPAction* PROTOBUF_NULLABLE on_change_;
    float min_value_;
    float max_value_;
    float initial_value_;
    float step_;
    bool enabled_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fslider_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RPSlider

// string field_id = 1 [json_name = "fieldId"];
inline void RPSlider::clear_field_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.field_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& RPSlider::field_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.ui.v1.RPSlider.field_id)
  return _internal_field_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RPSlider::set_field_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.field_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:proto.renderprotocol.ui.v1.RPSlider.field_id)
}
inline ::std::string* PROTOBUF_NONNULL RPSlider::mutable_field_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_field_id();
  // @@protoc_insertion_point(field_mutable:proto.renderprotocol.ui.v1.RPSlider.field_id)
  return _s;
}
inline const ::std::string& RPSlider::_internal_field_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.field_id_.Get();
}
inline void RPSlider::_internal_set_field_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.field_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RPSlider::_internal_mutable_field_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.field_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RPSlider::release_field_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.renderprotocol.ui.v1.RPSlider.field_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.field_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.field_id_.Set("", GetArena());
  }
  return released;
}
inline void RPSlider::set_allocated_field_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.field_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.field_id_.IsDefault()) {
    _impl_.field_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.renderprotocol.ui.v1.RPSlider.field_id)
}

// float min_value = 2 [json_name = "minValue"];
inline void RPSlider::clear_min_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.min_value_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
inline float RPSlider::min_value() const {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.ui.v1.RPSlider.min_value)
  return _internal_min_value();
}
inline void RPSlider::set_min_value(float value) {
  _internal_set_min_value(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:proto.renderprotocol.ui.v1.RPSlider.min_value)
}
inline float RPSlider::_internal_min_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.min_value_;
}
inline void RPSlider::_internal_set_min_value(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.min_value_ = value;
}

// float max_value = 3 [json_name = "maxValue"];
inline void RPSlider::clear_max_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_value_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
}
inline float RPSlider::max_value() const {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.ui.v1.RPSlider.max_value)
  return _internal_max_value();
}
inline void RPSlider::set_max_value(float value) {
  _internal_set_max_value(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:proto.renderprotocol.ui.v1.RPSlider.max_value)
}
inline float RPSlider::_internal_max_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.max_value_;
}
inline void RPSlider::_internal_set_max_value(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_value_ = value;
}

// optional float initial_value = 4 [json_name = "initialValue"];
inline bool RPSlider::has_initial_value() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000020U);
  return value;
}
inline void RPSlider::clear_initial_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.initial_value_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
}
inline float RPSlider::initial_value() const {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.ui.v1.RPSlider.initial_value)
  return _internal_initial_value();
}
inline void RPSlider::set_initial_value(float value) {
  _internal_set_initial_value(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:proto.renderprotocol.ui.v1.RPSlider.initial_value)
}
inline float RPSlider::_internal_initial_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.initial_value_;
}
inline void RPSlider::_internal_set_initial_value(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.initial_value_ = value;
}

// optional float step = 5 [json_name = "step"];
inline bool RPSlider::has_step() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000040U);
  return value;
}
inline void RPSlider::clear_step() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.step_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
}
inline float RPSlider::step() const {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.ui.v1.RPSlider.step)
  return _internal_step();
}
inline void RPSlider::set_step(float value) {
  _internal_set_step(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:proto.renderprotocol.ui.v1.RPSlider.step)
}
inline float RPSlider::_internal_step() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.step_;
}
inline void RPSlider::_internal_set_step(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.step_ = value;
}

// optional .proto.renderprotocol.ui.v1.RPColor active_color = 6 [json_name = "activeColor"];
inline bool RPSlider::has_active_color() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.active_color_ != nullptr);
  return value;
}
inline const ::proto::renderprotocol::ui::v1::RPColor& RPSlider::_internal_active_color() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::proto::renderprotocol::ui::v1::RPColor* p = _impl_.active_color_;
  return p != nullptr ? *p : *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<::proto::renderprotocol::ui::v1::RPColor>(&::proto::renderprotocol::ui::v1::RPColor_globals_);
}
inline const ::proto::renderprotocol::ui::v1::RPColor& RPSlider::active_color() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.ui.v1.RPSlider.active_color)
  return _internal_active_color();
}
inline void RPSlider::unsafe_arena_set_allocated_active_color(
    ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.active_color_);
  }
  _impl_.active_color_ = reinterpret_cast<::proto::renderprotocol::ui::v1::RPColor*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.renderprotocol.ui.v1.RPSlider.active_color)
}
inline ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE RPSlider::release_active_color() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::renderprotocol::ui::v1::RPColor* released = _impl_.active_color_;
  _impl_.active_color_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE RPSlider::unsafe_arena_release_active_color() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.renderprotocol.ui.v1.RPSlider.active_color)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::renderprotocol::ui::v1::RPColor* temp = _impl_.active_color_;
  _impl_.active_color_ = nullptr;
  return temp;
}
inline ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NONNULL RPSlider::_internal_mutable_active_color() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.active_color_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::proto::renderprotocol::ui::v1::RPColor>(GetArena());
    _impl_.active_color_ = reinterpret_cast<::proto::renderprotocol::ui::v1::RPColor*>(p);
  }
  return _impl_.active_color_;
}
inline ::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NONNULL RPSlider::mutable_active_color()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::renderprotocol::ui::v1::RPColor* _msg = _internal_mutable_active_color();
  // @@protoc_insertion_point(field_mutable:proto.renderprotocol.ui.v1.RPSlider.active_color)
  return _msg;
}
inline void RPSlider::set_allocated_active_color(::proto::renderprotocol::ui::v1::RPColor* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.active_color_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.active_color_ = reinterpret_cast<::proto::renderprotocol::ui::v1::RPColor*>(value);
  // @@protoc_insertion_point(field_set_allocated:proto.renderprotocol.ui.v1.RPSlider.active_color)
}

// bool enabled = 7 [json_name = "enabled"];
inline void RPSlider::clear_enabled() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enabled_ = false;
  ClearHasBit(_impl_._has_bits_[0], 0x00000080U);
}
inline bool RPSlider::enabled() const {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.ui.v1.RPSlider.enabled)
  return _internal_enabled();
}
inline void RPSlider::set_enabled(bool value) {
  _internal_set_enabled(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:proto.renderprotocol.ui.v1.RPSlider.enabled)
}
inline bool RPSlider::_internal_enabled() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.enabled_;
}
inline void RPSlider::_internal_set_enabled(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enabled_ = value;
}

// optional .proto.renderprotocol.ui.v1.RPAction on_change = 8 [json_name = "onChange"];
inline bool RPSlider::has_on_change() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  PROTOBUF_ASSUME(!value || _impl_.on_change_ != nullptr);
  return value;
}
inline const ::proto::renderprotocol::ui::v1::RPAction& RPSlider::_internal_on_change() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::proto::renderprotocol::ui::v1::RPAction* p = _impl_.on_change_;
  return p != nullptr ? *p : *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<::proto::renderprotocol::ui::v1::RPAction>(&::proto::renderprotocol::ui::v1::RPAction_globals_);
}
inline const ::proto::renderprotocol::ui::v1::RPAction& RPSlider::on_change() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.ui.v1.RPSlider.on_change)
  return _internal_on_change();
}
inline void RPSlider::unsafe_arena_set_allocated_on_change(
    ::proto::renderprotocol::ui::v1::RPAction* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.on_change_);
  }
  _impl_.on_change_ = reinterpret_cast<::proto::renderprotocol::ui::v1::RPAction*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.renderprotocol.ui.v1.RPSlider.on_change)
}
inline ::proto::renderprotocol::ui::v1::RPAction* PROTOBUF_NULLABLE RPSlider::release_on_change() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::proto::renderprotocol::ui::v1::RPAction* released = _impl_.on_change_;
  _impl_.on_change_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::proto::renderprotocol::ui::v1::RPAction* PROTOBUF_NULLABLE RPSlider::unsafe_arena_release_on_change() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.renderprotocol.ui.v1.RPSlider.on_change)

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::proto::renderprotocol::ui::v1::RPAction* temp = _impl_.on_change_;
  _impl_.on_change_ = nullptr;
  return temp;
}
inline ::proto::renderprotocol::ui::v1::RPAction* PROTOBUF_NONNULL RPSlider::_internal_mutable_on_change() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.on_change_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::proto::renderprotocol::ui::v1::RPAction>(GetArena());
    _impl_.on_change_ = reinterpret_cast<::proto::renderprotocol::ui::v1::RPAction*>(p);
  }
  return _impl_.on_change_;
}
inline ::proto::renderprotocol::ui::v1::RPAction* PROTOBUF_NONNULL RPSlider::mutable_on_change()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::proto::renderprotocol::ui::v1::RPAction* _msg = _internal_mutable_on_change();
  // @@protoc_insertion_point(field_mutable:proto.renderprotocol.ui.v1.RPSlider.on_change)
  return _msg;
}
inline void RPSlider::set_allocated_on_change(::proto::renderprotocol::ui::v1::RPAction* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.on_change_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }

  _impl_.on_change_ = reinterpret_cast<::proto::renderprotocol::ui::v1::RPAction*>(value);
  // @@protoc_insertion_point(field_set_allocated:proto.renderprotocol.ui.v1.RPSlider.on_change)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace ui
}  // namespace renderprotocol
}  // namespace proto


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fslider_2eproto_2epb_2eh
