// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_text_field.proto
// Protobuf C++ Version: 6.33.5

#include "proto/renderprotocol/ui/v1/rp_ui_text_field.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace proto {
namespace renderprotocol {
namespace ui {
namespace v1 {

inline constexpr RPTextField::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        field_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        placeholder_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        initial_value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        text_style_{nullptr},
        on_submit_{nullptr},
        keyboard_type_{static_cast< ::proto::renderprotocol::ui::v1::RPKeyboardType >(0)},
        max_length_{0},
        secure_entry_{false},
        enabled_{false} {}

template <typename>
PROTOBUF_CONSTEXPR RPTextField::RPTextField(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RPTextField_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RPTextFieldDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RPTextFieldDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RPTextFieldDefaultTypeInternal() {}
  union {
    RPTextField _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RPTextFieldDefaultTypeInternal _RPTextField_default_instance_;
}  // namespace v1
}  // namespace ui
}  // namespace renderprotocol
}  // namespace proto
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_5ffield_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_5ffield_2eproto = nullptr;
const ::uint32_t
    TableStruct_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_5ffield_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPTextField, _impl_._has_bits_),
        12, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPTextField, _impl_.field_id_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPTextField, _impl_.placeholder_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPTextField, _impl_.initial_value_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPTextField, _impl_.keyboard_type_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPTextField, _impl_.secure_entry_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPTextField, _impl_.max_length_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPTextField, _impl_.text_style_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPTextField, _impl_.enabled_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPTextField, _impl_.on_submit_),
        0,
        1,
        2,
        5,
        7,
        6,
        3,
        8,
        4,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::proto::renderprotocol::ui::v1::RPTextField)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::proto::renderprotocol::ui::v1::_RPTextField_default_instance_._instance,
};
const char descriptor_table_protodef_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_5ffield_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n1proto/renderprotocol/ui/v1/rp_ui_text_"
    "field.proto\022\032proto.renderprotocol.ui.v1\032"
    "-proto/renderprotocol/ui/v1/rp_ui_action"
    ".proto\032+proto/renderprotocol/ui/v1/rp_ui"
    "_text.proto\"\216\004\n\013RPTextField\022\031\n\010field_id\030"
    "\001 \001(\tR\007fieldId\022%\n\013placeholder\030\002 \001(\tH\000R\013p"
    "laceholder\210\001\001\022(\n\rinitial_value\030\003 \001(\tH\001R\014"
    "initialValue\210\001\001\022O\n\rkeyboard_type\030\004 \001(\0162*"
    ".proto.renderprotocol.ui.v1.RPKeyboardTy"
    "peR\014keyboardType\022!\n\014secure_entry\030\005 \001(\010R\013"
    "secureEntry\022\"\n\nmax_length\030\006 \001(\005H\002R\tmaxLe"
    "ngth\210\001\001\022K\n\ntext_style\030\007 \001(\0132\'.proto.rend"
    "erprotocol.ui.v1.RPTextStyleH\003R\ttextStyl"
    "e\210\001\001\022\030\n\007enabled\030\010 \001(\010R\007enabled\022F\n\ton_sub"
    "mit\030\t \001(\0132$.proto.renderprotocol.ui.v1.R"
    "PActionH\004R\010onSubmit\210\001\001B\016\n\014_placeholderB\020"
    "\n\016_initial_valueB\r\n\013_max_lengthB\r\n\013_text"
    "_styleB\014\n\n_on_submit*\335\001\n\016RPKeyboardType\022"
    " \n\034RP_KEYBOARD_TYPE_UNSPECIFIED\020\000\022\034\n\030RP_"
    "KEYBOARD_TYPE_DEFAULT\020\001\022\032\n\026RP_KEYBOARD_T"
    "YPE_EMAIL\020\002\022\033\n\027RP_KEYBOARD_TYPE_NUMBER\020\003"
    "\022\032\n\026RP_KEYBOARD_TYPE_PHONE\020\004\022\030\n\024RP_KEYBO"
    "ARD_TYPE_URL\020\005\022\034\n\030RP_KEYBOARD_TYPE_DECIM"
    "AL\020\006B\307\001\n\036com.proto.renderprotocol.ui.v1B"
    "\022RpUiTextFieldProtoH\001P\001\370\001\001\242\002\003PRU\252\002\032Proto"
    ".Renderprotocol.Ui.V1\272\002\000\312\002\032Proto\\Renderp"
    "rotocol\\Ui\\V1\342\002&Proto\\Renderprotocol\\Ui\\"
    "V1\\GPBMetadata\352\002\035Proto::Renderprotocol::"
    "Ui::V1b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_5ffield_2eproto_deps[2] = {
        &::descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5faction_2eproto,
        &::descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_2eproto,
};
static ::absl::once_flag descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_5ffield_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_5ffield_2eproto = {
    false,
    false,
    1134,
    descriptor_table_protodef_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_5ffield_2eproto,
    "proto/renderprotocol/ui/v1/rp_ui_text_field.proto",
    &descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_5ffield_2eproto_once,
    descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_5ffield_2eproto_deps,
    2,
    1,
    schemas,
    file_default_instances,
    TableStruct_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_5ffield_2eproto::offsets,
    file_level_enum_descriptors_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_5ffield_2eproto,
    file_level_service_descriptors_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_5ffield_2eproto,
};
namespace proto {
namespace renderprotocol {
namespace ui {
namespace v1 {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL RPKeyboardType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_5ffield_2eproto);
  return file_level_enum_descriptors_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_5ffield_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t RPKeyboardType_internal_data_[] = {
    458752u, 0u, };
// ===================================================================

class RPTextField::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RPTextField>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RPTextField, _impl_._has_bits_);
};

void RPTextField::clear_text_style() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.text_style_ != nullptr) _impl_.text_style_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
void RPTextField::clear_on_submit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.on_submit_ != nullptr) _impl_.on_submit_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
RPTextField::RPTextField(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RPTextField_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.renderprotocol.ui.v1.RPTextField)
}
PROTOBUF_NDEBUG_INLINE RPTextField::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::renderprotocol::ui::v1::RPTextField& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        field_id_(arena, from.field_id_),
        placeholder_(arena, from.placeholder_),
        initial_value_(arena, from.initial_value_) {}

RPTextField::RPTextField(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RPTextField& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RPTextField_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RPTextField* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.text_style_ = (CheckHasBit(cached_has_bits, 0x00000008U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.text_style_)
                : nullptr;
  _impl_.on_submit_ = (CheckHasBit(cached_has_bits, 0x00000010U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.on_submit_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, keyboard_type_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, keyboard_type_),
           offsetof(Impl_, enabled_) -
               offsetof(Impl_, keyboard_type_) +
               sizeof(Impl_::enabled_));

  // @@protoc_insertion_point(copy_constructor:proto.renderprotocol.ui.v1.RPTextField)
}
PROTOBUF_NDEBUG_INLINE RPTextField::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        field_id_(arena),
        placeholder_(arena),
        initial_value_(arena) {}

inline void RPTextField::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, text_style_),
           0,
           offsetof(Impl_, enabled_) -
               offsetof(Impl_, text_style_) +
               sizeof(Impl_::enabled_));
}
RPTextField::~RPTextField() {
  // @@protoc_insertion_point(destructor:proto.renderprotocol.ui.v1.RPTextField)
  SharedDtor(*this);
}
inline void RPTextField::SharedDtor(MessageLite& self) {
  RPTextField& this_ = static_cast<RPTextField&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.field_id_.Destroy();
  this_._impl_.placeholder_.Destroy();
  this_._impl_.initial_value_.Destroy();
  delete this_._impl_.text_style_;
  delete this_._impl_.on_submit_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RPTextField::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RPTextField(arena);
}
constexpr auto RPTextField::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RPTextField),
                                            alignof(RPTextField));
}
constexpr auto RPTextField::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RPTextField_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RPTextField::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RPTextField>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RPTextField::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RPTextField>(), &RPTextField::ByteSizeLong,
              &RPTextField::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RPTextField, _impl_._cached_size_),
          false,
      },
      &RPTextField::kDescriptorMethods,
      &descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_5ffield_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RPTextField_class_data_ =
        RPTextField::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RPTextField::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RPTextField_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RPTextField_class_data_.tc_table);
  return RPTextField_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 9, 2, 87, 2>
RPTextField::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RPTextField, _impl_._has_bits_),
    0, // no _extensions_
    9, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966784,  // skipmap
    offsetof(decltype(_table_), field_entries),
    9,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    RPTextField_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::renderprotocol::ui::v1::RPTextField>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string field_id = 1 [json_name = "fieldId"];
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(RPTextField, _impl_.field_id_)}},
    // optional string placeholder = 2 [json_name = "placeholder"];
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(RPTextField, _impl_.placeholder_)}},
    // optional string initial_value = 3 [json_name = "initialValue"];
    {::_pbi::TcParser::FastUS1,
     {26, 2, 0,
      PROTOBUF_FIELD_OFFSET(RPTextField, _impl_.initial_value_)}},
    // .proto.renderprotocol.ui.v1.RPKeyboardType keyboard_type = 4 [json_name = "keyboardType"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RPTextField, _impl_.keyboard_type_), 5>(),
     {32, 5, 0,
      PROTOBUF_FIELD_OFFSET(RPTextField, _impl_.keyboard_type_)}},
    // bool secure_entry = 5 [json_name = "secureEntry"];
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(RPTextField, _impl_.secure_entry_), 7>(),
     {40, 7, 0,
      PROTOBUF_FIELD_OFFSET(RPTextField, _impl_.secure_entry_)}},
    // optional int32 max_length = 6 [json_name = "maxLength"];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RPTextField, _impl_.max_length_), 6>(),
     {48, 6, 0,
      PROTOBUF_FIELD_OFFSET(RPTextField, _impl_.max_length_)}},
    // optional .proto.renderprotocol.ui.v1.RPTextStyle text_style = 7 [json_name = "textStyle"];
    {::_pbi::TcParser::FastMtS1,
     {58, 3, 0,
      PROTOBUF_FIELD_OFFSET(RPTextField, _impl_.text_style_)}},
    // bool enabled = 8 [json_name = "enabled"];
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(RPTextField, _impl_.enabled_), 8>(),
     {64, 8, 0,
      PROTOBUF_FIELD_OFFSET(RPTextField, _impl_.enabled_)}},
    // optional .proto.renderprotocol.ui.v1.RPAction on_submit = 9 [json_name = "onSubmit"];
    {::_pbi::TcParser::FastMtS1,
     {74, 4, 1,
      PROTOBUF_FIELD_OFFSET(RPTextField, _impl_.on_submit_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string field_id = 1 [json_name = "fieldId"];
    {PROTOBUF_FIELD_OFFSET(RPTextField, _impl_.field_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string placeholder = 2 [json_name = "placeholder"];
    {PROTOBUF_FIELD_OFFSET(RPTextField, _impl_.placeholder_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string initial_value = 3 [json_name = "initialValue"];
    {PROTOBUF_FIELD_OFFSET(RPTextField, _impl_.initial_value_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .proto.renderprotocol.ui.v1.RPKeyboardType keyboard_type = 4 [json_name = "keyboardType"];
    {PROTOBUF_FIELD_OFFSET(RPTextField, _impl_.keyboard_type_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // bool secure_entry = 5 [json_name = "secureEntry"];
    {PROTOBUF_FIELD_OFFSET(RPTextField, _impl_.secure_entry_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional int32 max_length = 6 [json_name = "maxLength"];
    {PROTOBUF_FIELD_OFFSET(RPTextField, _impl_.max_length_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional .proto.renderprotocol.ui.v1.RPTextStyle text_style = 7 [json_name = "textStyle"];
    {PROTOBUF_FIELD_OFFSET(RPTextField, _impl_.text_style_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // bool enabled = 8 [json_name = "enabled"];
    {PROTOBUF_FIELD_OFFSET(RPTextField, _impl_.enabled_), _Internal::kHasBitsOffset + 8, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional .proto.renderprotocol.ui.v1.RPAction on_submit = 9 [json_name = "onSubmit"];
    {PROTOBUF_FIELD_OFFSET(RPTextField, _impl_.on_submit_), _Internal::kHasBitsOffset + 4, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::proto::renderprotocol::ui::v1::RPTextStyle>()},
      {::_pbi::TcParser::GetTable<::proto::renderprotocol::ui::v1::RPAction>()},
  }},
  {{
    "\46\10\13\15\0\0\0\0\0\0\0\0\0\0\0\0"
    "proto.renderprotocol.ui.v1.RPTextField"
    "field_id"
    "placeholder"
    "initial_value"
  }},
};
PROTOBUF_NOINLINE void RPTextField::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.renderprotocol.ui.v1.RPTextField)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.field_id_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.placeholder_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.initial_value_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(_impl_.text_style_ != nullptr);
      _impl_.text_style_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      ABSL_DCHECK(_impl_.on_submit_ != nullptr);
      _impl_.on_submit_->Clear();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000000e0U)) {
    ::memset(&_impl_.keyboard_type_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.secure_entry_) -
        reinterpret_cast<char*>(&_impl_.keyboard_type_)) + sizeof(_impl_.secure_entry_));
  }
  _impl_.enabled_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RPTextField::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RPTextField& this_ = static_cast<const RPTextField&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RPTextField::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RPTextField& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.renderprotocol.ui.v1.RPTextField)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string field_id = 1 [json_name = "fieldId"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_field_id().empty()) {
      const ::std::string& _s = this_._internal_field_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.renderprotocol.ui.v1.RPTextField.field_id");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // optional string placeholder = 2 [json_name = "placeholder"];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    const ::std::string& _s = this_._internal_placeholder();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.renderprotocol.ui.v1.RPTextField.placeholder");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // optional string initial_value = 3 [json_name = "initialValue"];
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    const ::std::string& _s = this_._internal_initial_value();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.renderprotocol.ui.v1.RPTextField.initial_value");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // .proto.renderprotocol.ui.v1.RPKeyboardType keyboard_type = 4 [json_name = "keyboardType"];
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_keyboard_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          4, this_._internal_keyboard_type(), target);
    }
  }

  // bool secure_entry = 5 [json_name = "secureEntry"];
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    if (this_._internal_secure_entry() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          5, this_._internal_secure_entry(), target);
    }
  }

  // optional int32 max_length = 6 [json_name = "maxLength"];
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<6>(
            stream, this_._internal_max_length(), target);
  }

  // optional .proto.renderprotocol.ui.v1.RPTextStyle text_style = 7 [json_name = "textStyle"];
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        7, *this_._impl_.text_style_, this_._impl_.text_style_->GetCachedSize(), target,
        stream);
  }

  // bool enabled = 8 [json_name = "enabled"];
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    if (this_._internal_enabled() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          8, this_._internal_enabled(), target);
    }
  }

  // optional .proto.renderprotocol.ui.v1.RPAction on_submit = 9 [json_name = "onSubmit"];
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        9, *this_._impl_.on_submit_, this_._impl_.on_submit_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.renderprotocol.ui.v1.RPTextField)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RPTextField::ByteSizeLong(const MessageLite& base) {
  const RPTextField& this_ = static_cast<const RPTextField&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RPTextField::ByteSizeLong() const {
  const RPTextField& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.renderprotocol.ui.v1.RPTextField)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // string field_id = 1 [json_name = "fieldId"];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_field_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_field_id());
      }
    }
    // optional string placeholder = 2 [json_name = "placeholder"];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_placeholder());
    }
    // optional string initial_value = 3 [json_name = "initialValue"];
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_initial_value());
    }
    // optional .proto.renderprotocol.ui.v1.RPTextStyle text_style = 7 [json_name = "textStyle"];
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.text_style_);
    }
    // optional .proto.renderprotocol.ui.v1.RPAction on_submit = 9 [json_name = "onSubmit"];
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.on_submit_);
    }
    // .proto.renderprotocol.ui.v1.RPKeyboardType keyboard_type = 4 [json_name = "keyboardType"];
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_keyboard_type() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_keyboard_type());
      }
    }
    // optional int32 max_length = 6 [json_name = "maxLength"];
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_max_length());
    }
    // bool secure_entry = 5 [json_name = "secureEntry"];
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (this_._internal_secure_entry() != 0) {
        total_size += 2;
      }
    }
  }
   {
    // bool enabled = 8 [json_name = "enabled"];
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (this_._internal_enabled() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RPTextField::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<RPTextField*>(&to_msg);
  auto& from = static_cast<const RPTextField&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.renderprotocol.ui.v1.RPTextField)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_field_id().empty()) {
        _this->_internal_set_field_id(from._internal_field_id());
      } else {
        if (_this->_impl_.field_id_.IsDefault()) {
          _this->_internal_set_field_id("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_set_placeholder(from._internal_placeholder());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_internal_set_initial_value(from._internal_initial_value());
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(from._impl_.text_style_ != nullptr);
      if (_this->_impl_.text_style_ == nullptr) {
        _this->_impl_.text_style_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.text_style_);
      } else {
        _this->_impl_.text_style_->MergeFrom(*from._impl_.text_style_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      ABSL_DCHECK(from._impl_.on_submit_ != nullptr);
      if (_this->_impl_.on_submit_ == nullptr) {
        _this->_impl_.on_submit_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.on_submit_);
      } else {
        _this->_impl_.on_submit_->MergeFrom(*from._impl_.on_submit_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_keyboard_type() != 0) {
        _this->_impl_.keyboard_type_ = from._impl_.keyboard_type_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      _this->_impl_.max_length_ = from._impl_.max_length_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (from._internal_secure_entry() != 0) {
        _this->_impl_.secure_entry_ = from._impl_.secure_entry_;
      }
    }
  }
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    if (from._internal_enabled() != 0) {
      _this->_impl_.enabled_ = from._impl_.enabled_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void RPTextField::CopyFrom(const RPTextField& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.renderprotocol.ui.v1.RPTextField)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RPTextField::InternalSwap(RPTextField* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.field_id_, &other->_impl_.field_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.placeholder_, &other->_impl_.placeholder_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.initial_value_, &other->_impl_.initial_value_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RPTextField, _impl_.enabled_)
      + sizeof(RPTextField::_impl_.enabled_)
      - PROTOBUF_FIELD_OFFSET(RPTextField, _impl_.text_style_)>(
          reinterpret_cast<char*>(&_impl_.text_style_),
          reinterpret_cast<char*>(&other->_impl_.text_style_));
}

::google::protobuf::Metadata RPTextField::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace ui
}  // namespace renderprotocol
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ftext_5ffield_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
