// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_shape.proto
// Protobuf C++ Version: 7.34.0

#include "proto/renderprotocol/ui/v1/rp_ui_shape.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace proto {
namespace renderprotocol {
namespace ui {
namespace v1 {

inline constexpr RPShapeRoundedRectangle::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        radius_{0} {}

template <typename>
constexpr RPShapeRoundedRectangle::RPShapeRoundedRectangle(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RPShapeRoundedRectangle_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct RPShapeRoundedRectangleDefaultTypeInternal {
  constexpr RPShapeRoundedRectangleDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RPShapeRoundedRectangleDefaultTypeInternal() {}
  union {
    RPShapeRoundedRectangle _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RPShapeRoundedRectangleDefaultTypeInternal _RPShapeRoundedRectangle_default_instance_;
template <typename>
constexpr RPShapeRectangle::RPShapeRectangle(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(RPShapeRectangle_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct RPShapeRectangleDefaultTypeInternal {
  constexpr RPShapeRectangleDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RPShapeRectangleDefaultTypeInternal() {}
  union {
    RPShapeRectangle _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RPShapeRectangleDefaultTypeInternal _RPShapeRectangle_default_instance_;
template <typename>
constexpr RPShapeEllipse::RPShapeEllipse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(RPShapeEllipse_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct RPShapeEllipseDefaultTypeInternal {
  constexpr RPShapeEllipseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RPShapeEllipseDefaultTypeInternal() {}
  union {
    RPShapeEllipse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RPShapeEllipseDefaultTypeInternal _RPShapeEllipse_default_instance_;
template <typename>
constexpr RPShapeCircle::RPShapeCircle(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(RPShapeCircle_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct RPShapeCircleDefaultTypeInternal {
  constexpr RPShapeCircleDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RPShapeCircleDefaultTypeInternal() {}
  union {
    RPShapeCircle _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RPShapeCircleDefaultTypeInternal _RPShapeCircle_default_instance_;
template <typename>
constexpr RPShapeCapsule::RPShapeCapsule(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(RPShapeCapsule_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct RPShapeCapsuleDefaultTypeInternal {
  constexpr RPShapeCapsuleDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RPShapeCapsuleDefaultTypeInternal() {}
  union {
    RPShapeCapsule _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RPShapeCapsuleDefaultTypeInternal _RPShapeCapsule_default_instance_;
}  // namespace v1
}  // namespace ui
}  // namespace renderprotocol
}  // namespace proto
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fshape_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fshape_2eproto = nullptr;
const ::uint32_t
    TableStruct_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fshape_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x000, // bitmap
        0x000, // bitmap
        0x000, // bitmap
        0x000, // bitmap
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPShapeRoundedRectangle, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPShapeRoundedRectangle, _impl_.radius_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::proto::renderprotocol::ui::v1::RPShapeRectangle)},
        {1, sizeof(::proto::renderprotocol::ui::v1::RPShapeCircle)},
        {2, sizeof(::proto::renderprotocol::ui::v1::RPShapeEllipse)},
        {3, sizeof(::proto::renderprotocol::ui::v1::RPShapeCapsule)},
        {4, sizeof(::proto::renderprotocol::ui::v1::RPShapeRoundedRectangle)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::proto::renderprotocol::ui::v1::_RPShapeRectangle_default_instance_._instance,
    &::proto::renderprotocol::ui::v1::_RPShapeCircle_default_instance_._instance,
    &::proto::renderprotocol::ui::v1::_RPShapeEllipse_default_instance_._instance,
    &::proto::renderprotocol::ui::v1::_RPShapeCapsule_default_instance_._instance,
    &::proto::renderprotocol::ui::v1::_RPShapeRoundedRectangle_default_instance_._instance,
};
const char descriptor_table_protodef_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fshape_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n,proto/renderprotocol/ui/v1/rp_ui_shape"
    ".proto\022\032proto.renderprotocol.ui.v1\"\022\n\020RP"
    "ShapeRectangle\"\017\n\rRPShapeCircle\"\020\n\016RPSha"
    "peEllipse\"\020\n\016RPShapeCapsule\"1\n\027RPShapeRo"
    "undedRectangle\022\026\n\006radius\030\001 \001(\002R\006radiusB\303"
    "\001\n\036com.proto.renderprotocol.ui.v1B\016RpUiS"
    "hapeProtoH\001P\001\370\001\001\242\002\003PRU\252\002\032Proto.Renderpro"
    "tocol.Ui.V1\272\002\000\312\002\032Proto\\Renderprotocol\\Ui"
    "\\V1\342\002&Proto\\Renderprotocol\\Ui\\V1\\GPBMeta"
    "data\352\002\035Proto::Renderprotocol::Ui::V1b\006pr"
    "oto3"
};
static ::absl::once_flag descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fshape_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fshape_2eproto = {
    false,
    false,
    404,
    descriptor_table_protodef_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fshape_2eproto,
    "proto/renderprotocol/ui/v1/rp_ui_shape.proto",
    &descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fshape_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fshape_2eproto::offsets,
    file_level_enum_descriptors_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fshape_2eproto,
    file_level_service_descriptors_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fshape_2eproto,
};
namespace proto {
namespace renderprotocol {
namespace ui {
namespace v1 {
// ===================================================================

class RPShapeRectangle::_Internal {
 public:
};

RPShapeRectangle::RPShapeRectangle(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, RPShapeRectangle_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:proto.renderprotocol.ui.v1.RPShapeRectangle)
}
RPShapeRectangle::RPShapeRectangle(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RPShapeRectangle& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, RPShapeRectangle_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RPShapeRectangle* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:proto.renderprotocol.ui.v1.RPShapeRectangle)
}

inline void* PROTOBUF_NONNULL RPShapeRectangle::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RPShapeRectangle(arena);
}
constexpr auto RPShapeRectangle::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(RPShapeRectangle),
                                            alignof(RPShapeRectangle));
}
constexpr auto RPShapeRectangle::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RPShapeRectangle_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &RPShapeRectangle::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<RPShapeRectangle>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RPShapeRectangle::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<RPShapeRectangle>(), &RPShapeRectangle::ByteSizeLong,
              &RPShapeRectangle::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RPShapeRectangle, _impl_._cached_size_),
          false,
      },
      &RPShapeRectangle::kDescriptorMethods,
      &descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fshape_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RPShapeRectangle_class_data_ =
        RPShapeRectangle::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RPShapeRectangle::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RPShapeRectangle_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RPShapeRectangle_class_data_.tc_table);
  return RPShapeRectangle_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
RPShapeRectangle::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RPShapeRectangle,
                          _impl_._cached_size_),  // no hasbits
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RPShapeRectangle_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::renderprotocol::ui::v1::RPShapeRectangle>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata RPShapeRectangle::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RPShapeCircle::_Internal {
 public:
};

RPShapeCircle::RPShapeCircle(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, RPShapeCircle_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:proto.renderprotocol.ui.v1.RPShapeCircle)
}
RPShapeCircle::RPShapeCircle(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RPShapeCircle& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, RPShapeCircle_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RPShapeCircle* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:proto.renderprotocol.ui.v1.RPShapeCircle)
}

inline void* PROTOBUF_NONNULL RPShapeCircle::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RPShapeCircle(arena);
}
constexpr auto RPShapeCircle::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(RPShapeCircle),
                                            alignof(RPShapeCircle));
}
constexpr auto RPShapeCircle::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RPShapeCircle_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &RPShapeCircle::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<RPShapeCircle>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RPShapeCircle::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<RPShapeCircle>(), &RPShapeCircle::ByteSizeLong,
              &RPShapeCircle::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RPShapeCircle, _impl_._cached_size_),
          false,
      },
      &RPShapeCircle::kDescriptorMethods,
      &descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fshape_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RPShapeCircle_class_data_ =
        RPShapeCircle::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RPShapeCircle::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RPShapeCircle_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RPShapeCircle_class_data_.tc_table);
  return RPShapeCircle_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
RPShapeCircle::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RPShapeCircle,
                          _impl_._cached_size_),  // no hasbits
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RPShapeCircle_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::renderprotocol::ui::v1::RPShapeCircle>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata RPShapeCircle::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RPShapeEllipse::_Internal {
 public:
};

RPShapeEllipse::RPShapeEllipse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, RPShapeEllipse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:proto.renderprotocol.ui.v1.RPShapeEllipse)
}
RPShapeEllipse::RPShapeEllipse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RPShapeEllipse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, RPShapeEllipse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RPShapeEllipse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:proto.renderprotocol.ui.v1.RPShapeEllipse)
}

inline void* PROTOBUF_NONNULL RPShapeEllipse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RPShapeEllipse(arena);
}
constexpr auto RPShapeEllipse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(RPShapeEllipse),
                                            alignof(RPShapeEllipse));
}
constexpr auto RPShapeEllipse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RPShapeEllipse_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &RPShapeEllipse::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<RPShapeEllipse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RPShapeEllipse::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<RPShapeEllipse>(), &RPShapeEllipse::ByteSizeLong,
              &RPShapeEllipse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RPShapeEllipse, _impl_._cached_size_),
          false,
      },
      &RPShapeEllipse::kDescriptorMethods,
      &descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fshape_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RPShapeEllipse_class_data_ =
        RPShapeEllipse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RPShapeEllipse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RPShapeEllipse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RPShapeEllipse_class_data_.tc_table);
  return RPShapeEllipse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
RPShapeEllipse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RPShapeEllipse,
                          _impl_._cached_size_),  // no hasbits
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RPShapeEllipse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::renderprotocol::ui::v1::RPShapeEllipse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata RPShapeEllipse::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RPShapeCapsule::_Internal {
 public:
};

RPShapeCapsule::RPShapeCapsule(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, RPShapeCapsule_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:proto.renderprotocol.ui.v1.RPShapeCapsule)
}
RPShapeCapsule::RPShapeCapsule(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RPShapeCapsule& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, RPShapeCapsule_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RPShapeCapsule* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:proto.renderprotocol.ui.v1.RPShapeCapsule)
}

inline void* PROTOBUF_NONNULL RPShapeCapsule::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RPShapeCapsule(arena);
}
constexpr auto RPShapeCapsule::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(RPShapeCapsule),
                                            alignof(RPShapeCapsule));
}
constexpr auto RPShapeCapsule::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RPShapeCapsule_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &RPShapeCapsule::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<RPShapeCapsule>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RPShapeCapsule::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<RPShapeCapsule>(), &RPShapeCapsule::ByteSizeLong,
              &RPShapeCapsule::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RPShapeCapsule, _impl_._cached_size_),
          false,
      },
      &RPShapeCapsule::kDescriptorMethods,
      &descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fshape_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RPShapeCapsule_class_data_ =
        RPShapeCapsule::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RPShapeCapsule::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RPShapeCapsule_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RPShapeCapsule_class_data_.tc_table);
  return RPShapeCapsule_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
RPShapeCapsule::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RPShapeCapsule,
                          _impl_._cached_size_),  // no hasbits
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RPShapeCapsule_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::renderprotocol::ui::v1::RPShapeCapsule>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata RPShapeCapsule::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RPShapeRoundedRectangle::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RPShapeRoundedRectangle>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RPShapeRoundedRectangle, _impl_._has_bits_);
};

RPShapeRoundedRectangle::RPShapeRoundedRectangle(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RPShapeRoundedRectangle_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.renderprotocol.ui.v1.RPShapeRoundedRectangle)
}
RPShapeRoundedRectangle::RPShapeRoundedRectangle(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RPShapeRoundedRectangle& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RPShapeRoundedRectangle_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE RPShapeRoundedRectangle::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void RPShapeRoundedRectangle::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.radius_ = {};
}
RPShapeRoundedRectangle::~RPShapeRoundedRectangle() {
  // @@protoc_insertion_point(destructor:proto.renderprotocol.ui.v1.RPShapeRoundedRectangle)
  SharedDtor(*this);
}
inline void RPShapeRoundedRectangle::SharedDtor(MessageLite& self) {
  RPShapeRoundedRectangle& this_ = static_cast<RPShapeRoundedRectangle&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RPShapeRoundedRectangle::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RPShapeRoundedRectangle(arena);
}
constexpr auto RPShapeRoundedRectangle::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(RPShapeRoundedRectangle),
                                            alignof(RPShapeRoundedRectangle));
}
constexpr auto RPShapeRoundedRectangle::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RPShapeRoundedRectangle_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &RPShapeRoundedRectangle::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RPShapeRoundedRectangle>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RPShapeRoundedRectangle::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RPShapeRoundedRectangle>(), &RPShapeRoundedRectangle::ByteSizeLong,
              &RPShapeRoundedRectangle::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RPShapeRoundedRectangle, _impl_._cached_size_),
          false,
      },
      &RPShapeRoundedRectangle::kDescriptorMethods,
      &descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fshape_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RPShapeRoundedRectangle_class_data_ =
        RPShapeRoundedRectangle::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RPShapeRoundedRectangle::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RPShapeRoundedRectangle_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RPShapeRoundedRectangle_class_data_.tc_table);
  return RPShapeRoundedRectangle_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
RPShapeRoundedRectangle::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RPShapeRoundedRectangle, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RPShapeRoundedRectangle_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::renderprotocol::ui::v1::RPShapeRoundedRectangle>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // float radius = 1 [json_name = "radius"];
    {::_pbi::TcParser::FastF32S1,
     {13, 0, 0,
      PROTOBUF_FIELD_OFFSET(RPShapeRoundedRectangle, _impl_.radius_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float radius = 1 [json_name = "radius"];
    {PROTOBUF_FIELD_OFFSET(RPShapeRoundedRectangle, _impl_.radius_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void RPShapeRoundedRectangle::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.renderprotocol.ui.v1.RPShapeRoundedRectangle)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.radius_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RPShapeRoundedRectangle::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RPShapeRoundedRectangle& this_ = static_cast<const RPShapeRoundedRectangle&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RPShapeRoundedRectangle::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RPShapeRoundedRectangle& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.renderprotocol.ui.v1.RPShapeRoundedRectangle)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // float radius = 1 [json_name = "radius"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_radius()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          1, this_._internal_radius(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.renderprotocol.ui.v1.RPShapeRoundedRectangle)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RPShapeRoundedRectangle::ByteSizeLong(const MessageLite& base) {
  const RPShapeRoundedRectangle& this_ = static_cast<const RPShapeRoundedRectangle&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RPShapeRoundedRectangle::ByteSizeLong() const {
  const RPShapeRoundedRectangle& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.renderprotocol.ui.v1.RPShapeRoundedRectangle)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // float radius = 1 [json_name = "radius"];
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_radius()) != 0) {
        total_size += 5;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RPShapeRoundedRectangle::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<RPShapeRoundedRectangle*>(&to_msg);
  auto& from = static_cast<const RPShapeRoundedRectangle&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.renderprotocol.ui.v1.RPShapeRoundedRectangle)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (::absl::bit_cast<::uint32_t>(from._internal_radius()) != 0) {
      _this->_impl_.radius_ = from._impl_.radius_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void RPShapeRoundedRectangle::CopyFrom(const RPShapeRoundedRectangle& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.renderprotocol.ui.v1.RPShapeRoundedRectangle)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RPShapeRoundedRectangle::InternalSwap(RPShapeRoundedRectangle* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.radius_, other->_impl_.radius_);
}

::google::protobuf::Metadata RPShapeRoundedRectangle::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace ui
}  // namespace renderprotocol
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fshape_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
