// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_bottom_nav_bar.proto
// Protobuf C++ Version: 7.35.0

#include "proto/renderprotocol/ui/v1/rp_ui_bottom_nav_bar.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::proto::renderprotocol::ui::v1::RPBottomNavBar
        {&::_pbi::kDescriptorMethods, &::descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fbottom_5fnav_5fbar_2eproto, /* tracker*/ nullptr,},
        // ::proto::renderprotocol::ui::v1::RPBottomNavItem
        {&::_pbi::kDescriptorMethods, &::descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fbottom_5fnav_5fbar_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
namespace proto {
namespace renderprotocol {
namespace ui {
namespace v1 {
class RPBottomNavItem::_Internal {
 public:
  using HasBits = decltype(::std::declval<RPBottomNavItem>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RPBottomNavItem, _impl_._has_bits_);
};

constexpr RPBottomNavItem::ParseTableT_ RPBottomNavItem::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(RPBottomNavItem, _impl_._has_bits_),
      0, // no _extensions_
      3, 24,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967288,  // skipmap
      offsetof(ParseTableT_, field_entries),
      3,  // num_field_entries
      2,  // num_aux_entries
      offsetof(ParseTableT_, aux_entries),
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::proto::renderprotocol::ui::v1::RPBottomNavItem>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
      // .proto.renderprotocol.ui.v1.RPIcon icon = 1 [json_name = "icon"];
      {::_pbi::TcParser::FastMtS1,
       {10, 1, 0,
        PROTOBUF_FIELD_OFFSET(RPBottomNavItem, _impl_.icon_)}},
      // optional string label = 2 [json_name = "label"];
      {::_pbi::TcParser::FastUS1,
       {18, 0, 0,
        PROTOBUF_FIELD_OFFSET(RPBottomNavItem, _impl_.label_)}},
      // .proto.renderprotocol.ui.v1.RPAction action = 3 [json_name = "action"];
      {::_pbi::TcParser::FastMtS1,
       {26, 2, 1,
        PROTOBUF_FIELD_OFFSET(RPBottomNavItem, _impl_.action_)}},
    }}, {{
      65535, 65535
    }}, {{
      // .proto.renderprotocol.ui.v1.RPIcon icon = 1 [json_name = "icon"];
      {PROTOBUF_FIELD_OFFSET(RPBottomNavItem, _impl_.icon_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
      // optional string label = 2 [json_name = "label"];
      {PROTOBUF_FIELD_OFFSET(RPBottomNavItem, _impl_.label_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // .proto.renderprotocol.ui.v1.RPAction action = 3 [json_name = "action"];
      {PROTOBUF_FIELD_OFFSET(RPBottomNavItem, _impl_.action_), _Internal::kHasBitsOffset + 2, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    }},
    {{
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::proto::renderprotocol::ui::v1::RPIcon>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::proto::renderprotocol::ui::v1::RPIcon_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::proto::renderprotocol::ui::v1::RPAction>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::proto::renderprotocol::ui::v1::RPAction_globals_},
        #endif
    }},
    {{
      "\52\0\5\0\0\0\0\0"
      "proto.renderprotocol.ui.v1.RPBottomNavItem"
      "label"
    }},
  };
}


inline constexpr RPBottomNavItem::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        label_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        icon_{nullptr},
        action_{nullptr} {}

template <typename>
constexpr RPBottomNavItem::RPBottomNavItem(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL RPBottomNavItem::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RPBottomNavItem(arena);
}
constexpr auto RPBottomNavItem::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RPBottomNavItem), alignof(RPBottomNavItem));
}
constexpr auto RPBottomNavItem::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &RPBottomNavItem::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RPBottomNavItem>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RPBottomNavItem::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RPBottomNavItem>(), &RPBottomNavItem::ByteSizeLong,
              &RPBottomNavItem::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RPBottomNavItem, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[1],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fbottom_5fnav_5fbar_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct RPBottomNavItemGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr RPBottomNavItemGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 RPBottomNavItem_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(RPBottomNavItem::InternalGenerateClassData_(
            _default, &RPBottomNavItem_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<RPBottomNavItem>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~RPBottomNavItemGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) RPBottomNavItem _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<RPBottomNavItem>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(RPBottomNavItemGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST RPBottomNavItemGlobalsTypeInternal RPBottomNavItem_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* RPBottomNavItem_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return RPBottomNavItem_globals_.GetClassData();
#else
  return RPBottomNavItem_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class RPBottomNavBar::_Internal {
 public:
  using HasBits = decltype(::std::declval<RPBottomNavBar>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RPBottomNavBar, _impl_._has_bits_);
};

constexpr RPBottomNavBar::ParseTableT_ RPBottomNavBar::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(RPBottomNavBar, _impl_._has_bits_),
      0, // no _extensions_
      5, 56,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967264,  // skipmap
      offsetof(ParseTableT_, field_entries),
      5,  // num_field_entries
      4,  // num_aux_entries
      offsetof(ParseTableT_, aux_entries),
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::proto::renderprotocol::ui::v1::RPBottomNavBar>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
      // repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];
      {::_pbi::TcParser::FastMtR1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(RPBottomNavBar, _impl_.items_)}},
      // optional int32 selected_index = 2 [json_name = "selectedIndex"];
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RPBottomNavBar, _impl_.selected_index_), 4>(),
       {16, 4, 0,
        PROTOBUF_FIELD_OFFSET(RPBottomNavBar, _impl_.selected_index_)}},
      // optional .proto.renderprotocol.ui.v1.RPColor background_color = 3 [json_name = "backgroundColor"];
      {::_pbi::TcParser::FastMtS1,
       {26, 1, 1,
        PROTOBUF_FIELD_OFFSET(RPBottomNavBar, _impl_.background_color_)}},
      // optional .proto.renderprotocol.ui.v1.RPColor selected_color = 4 [json_name = "selectedColor"];
      {::_pbi::TcParser::FastMtS1,
       {34, 2, 2,
        PROTOBUF_FIELD_OFFSET(RPBottomNavBar, _impl_.selected_color_)}},
      // optional .proto.renderprotocol.ui.v1.RPColor unselected_color = 5 [json_name = "unselectedColor"];
      {::_pbi::TcParser::FastMtS1,
       {42, 3, 3,
        PROTOBUF_FIELD_OFFSET(RPBottomNavBar, _impl_.unselected_color_)}},
      {::_pbi::TcParser::MiniParse, {}},
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, {{
      // repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];
      {PROTOBUF_FIELD_OFFSET(RPBottomNavBar, _impl_.items_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
      // optional int32 selected_index = 2 [json_name = "selectedIndex"];
      {PROTOBUF_FIELD_OFFSET(RPBottomNavBar, _impl_.selected_index_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
      // optional .proto.renderprotocol.ui.v1.RPColor background_color = 3 [json_name = "backgroundColor"];
      {PROTOBUF_FIELD_OFFSET(RPBottomNavBar, _impl_.background_color_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
      // optional .proto.renderprotocol.ui.v1.RPColor selected_color = 4 [json_name = "selectedColor"];
      {PROTOBUF_FIELD_OFFSET(RPBottomNavBar, _impl_.selected_color_), _Internal::kHasBitsOffset + 2, 2, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
      // optional .proto.renderprotocol.ui.v1.RPColor unselected_color = 5 [json_name = "unselectedColor"];
      {PROTOBUF_FIELD_OFFSET(RPBottomNavBar, _impl_.unselected_color_), _Internal::kHasBitsOffset + 3, 3, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    }},
    {{
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::proto::renderprotocol::ui::v1::RPBottomNavItem>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::proto::renderprotocol::ui::v1::RPBottomNavItem_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::proto::renderprotocol::ui::v1::RPColor>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::proto::renderprotocol::ui::v1::RPColor_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::proto::renderprotocol::ui::v1::RPColor>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::proto::renderprotocol::ui::v1::RPColor_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::proto::renderprotocol::ui::v1::RPColor>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::proto::renderprotocol::ui::v1::RPColor_globals_},
        #endif
    }},
    {{
    }},
  };
}


inline constexpr RPBottomNavBar::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        items_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::proto::renderprotocol::ui::v1::RPBottomNavBar,
            PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPBottomNavBar, _impl_.items_)>()
         }
        ,
        background_color_{nullptr},
        selected_color_{nullptr},
        unselected_color_{nullptr},
        selected_index_{0} {}

template <typename>
constexpr RPBottomNavBar::RPBottomNavBar(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL RPBottomNavBar::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RPBottomNavBar(arena);
}
constexpr auto RPBottomNavBar::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RPBottomNavBar), alignof(RPBottomNavBar));
}
constexpr auto RPBottomNavBar::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &RPBottomNavBar::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RPBottomNavBar>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RPBottomNavBar::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RPBottomNavBar>(), &RPBottomNavBar::ByteSizeLong,
              &RPBottomNavBar::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RPBottomNavBar, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fbottom_5fnav_5fbar_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct RPBottomNavBarGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr RPBottomNavBarGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 RPBottomNavBar_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(RPBottomNavBar::InternalGenerateClassData_(
            _default, &RPBottomNavBar_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<RPBottomNavBar>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~RPBottomNavBarGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) RPBottomNavBar _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<RPBottomNavBar>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(RPBottomNavBarGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST RPBottomNavBarGlobalsTypeInternal RPBottomNavBar_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* RPBottomNavBar_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return RPBottomNavBar_globals_.GetClassData();
#else
  return RPBottomNavBar_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
}  // namespace v1
}  // namespace ui
}  // namespace renderprotocol
}  // namespace proto
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fbottom_5fnav_5fbar_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fbottom_5fnav_5fbar_2eproto = nullptr;
const ::uint32_t
    TableStruct_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fbottom_5fnav_5fbar_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPBottomNavBar, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPBottomNavBar, _impl_.items_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPBottomNavBar, _impl_.selected_index_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPBottomNavBar, _impl_.background_color_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPBottomNavBar, _impl_.selected_color_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPBottomNavBar, _impl_.unselected_color_),
        0,
        4,
        1,
        2,
        3,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPBottomNavItem, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPBottomNavItem, _impl_.icon_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPBottomNavItem, _impl_.label_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPBottomNavItem, _impl_.action_),
        1,
        0,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::proto::renderprotocol::ui::v1::RPBottomNavBar)},
        {13, sizeof(::proto::renderprotocol::ui::v1::RPBottomNavItem)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::proto::renderprotocol::ui::v1::RPBottomNavBar_globals_,
        &::proto::renderprotocol::ui::v1::RPBottomNavItem_globals_,
};
const char descriptor_table_protodef_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fbottom_5fnav_5fbar_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n5proto/renderprotocol/ui/v1/rp_ui_botto"
    "m_nav_bar.proto\022\032proto.renderprotocol.ui"
    ".v1\032-proto/renderprotocol/ui/v1/rp_ui_ac"
    "tion.proto\032,proto/renderprotocol/ui/v1/r"
    "p_ui_color.proto\032+proto/renderprotocol/u"
    "i/v1/rp_ui_icon.proto\"\312\003\n\016RPBottomNavBar"
    "\022A\n\005items\030\001 \003(\0132+.proto.renderprotocol.u"
    "i.v1.RPBottomNavItemR\005items\022*\n\016selected_"
    "index\030\002 \001(\005H\000R\rselectedIndex\210\001\001\022S\n\020backg"
    "round_color\030\003 \001(\0132#.proto.renderprotocol"
    ".ui.v1.RPColorH\001R\017backgroundColor\210\001\001\022O\n\016"
    "selected_color\030\004 \001(\0132#.proto.renderproto"
    "col.ui.v1.RPColorH\002R\rselectedColor\210\001\001\022S\n"
    "\020unselected_color\030\005 \001(\0132#.proto.renderpr"
    "otocol.ui.v1.RPColorH\003R\017unselectedColor\210"
    "\001\001B\021\n\017_selected_indexB\023\n\021_background_col"
    "orB\021\n\017_selected_colorB\023\n\021_unselected_col"
    "or\"\254\001\n\017RPBottomNavItem\0226\n\004icon\030\001 \001(\0132\".p"
    "roto.renderprotocol.ui.v1.RPIconR\004icon\022\031"
    "\n\005label\030\002 \001(\tH\000R\005label\210\001\001\022<\n\006action\030\003 \001("
    "\0132$.proto.renderprotocol.ui.v1.RPActionR"
    "\006actionB\010\n\006_labelB\312\001\n\036com.proto.renderpr"
    "otocol.ui.v1B\025RpUiBottomNavBarProtoH\001P\001\370"
    "\001\001\242\002\003PRU\252\002\032Proto.Renderprotocol.Ui.V1\272\002\000"
    "\312\002\032Proto\\Renderprotocol\\Ui\\V1\342\002&Proto\\Re"
    "nderprotocol\\Ui\\V1\\GPBMetadata\352\002\035Proto::"
    "Renderprotocol::Ui::V1b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fbottom_5fnav_5fbar_2eproto_deps[3] = {
        &::descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5faction_2eproto,
        &::descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fcolor_2eproto,
        &::descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ficon_2eproto,
};
static ::absl::once_flag descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fbottom_5fnav_5fbar_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fbottom_5fnav_5fbar_2eproto = {
    false,
    false,
    1070,
    descriptor_table_protodef_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fbottom_5fnav_5fbar_2eproto,
    "proto/renderprotocol/ui/v1/rp_ui_bottom_nav_bar.proto",
    &descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fbottom_5fnav_5fbar_2eproto_once,
    descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fbottom_5fnav_5fbar_2eproto_deps,
    3,
    2,
    schemas,
    file_message_globals,
    TableStruct_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fbottom_5fnav_5fbar_2eproto::offsets,
    file_level_enum_descriptors_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fbottom_5fnav_5fbar_2eproto,
    file_level_service_descriptors_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fbottom_5fnav_5fbar_2eproto,
};
namespace proto {
namespace renderprotocol {
namespace ui {
namespace v1 {
// ===================================================================

void RPBottomNavBar::clear_background_color() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.background_color_ != nullptr) _impl_.background_color_->Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
void RPBottomNavBar::clear_selected_color() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.selected_color_ != nullptr) _impl_.selected_color_->Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
void RPBottomNavBar::clear_unselected_color() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.unselected_color_ != nullptr) _impl_.unselected_color_->Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
RPBottomNavBar::RPBottomNavBar(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RPBottomNavBar_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.renderprotocol.ui.v1.RPBottomNavBar)
}
PROTOBUF_NDEBUG_INLINE RPBottomNavBar::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::renderprotocol::ui::v1::RPBottomNavBar& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        items_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::proto::renderprotocol::ui::v1::RPBottomNavBar,
              PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPBottomNavBar, _impl_.items_)>()
          , from.items_
        }
     {}

RPBottomNavBar::RPBottomNavBar(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RPBottomNavBar& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RPBottomNavBar_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RPBottomNavBar* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.background_color_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.background_color_)
                : nullptr;
  _impl_.selected_color_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.selected_color_)
                : nullptr;
  _impl_.unselected_color_ = (CheckHasBit(cached_has_bits, 0x00000008U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.unselected_color_)
                : nullptr;
  _impl_.selected_index_ = from._impl_.selected_index_;

  // @@protoc_insertion_point(copy_constructor:proto.renderprotocol.ui.v1.RPBottomNavBar)
}
PROTOBUF_NDEBUG_INLINE RPBottomNavBar::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        items_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::proto::renderprotocol::ui::v1::RPBottomNavBar,
            PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPBottomNavBar, _impl_.items_)>()
         }
     {}

inline void RPBottomNavBar::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, background_color_),
           0,
           offsetof(Impl_, selected_index_) -
               offsetof(Impl_, background_color_) +
               sizeof(Impl_::selected_index_));
}
RPBottomNavBar::~RPBottomNavBar() {
  // @@protoc_insertion_point(destructor:proto.renderprotocol.ui.v1.RPBottomNavBar)
  SharedDtor(*this);
}
inline void RPBottomNavBar::SharedDtor(MessageLite& self) {
  RPBottomNavBar& this_ = static_cast<RPBottomNavBar&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.background_color_;
  delete this_._impl_.selected_color_;
  delete this_._impl_.unselected_color_;
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RPBottomNavBar_class_data_ =
        RPBottomNavBar::InternalGenerateClassData_(RPBottomNavBar_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RPBottomNavBar::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RPBottomNavBar_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RPBottomNavBar_class_data_.tc_table);
  return RPBottomNavBar_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RPBottomNavBar::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RPBottomNavBar_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&RPBottomNavBar_globals_));
  return RPBottomNavBar_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const RPBottomNavBar::ParseTableT_
    RPBottomNavBar::_table_ =
        RPBottomNavBar::InternalGenerateParseTable_(RPBottomNavBar_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void RPBottomNavBar::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.renderprotocol.ui.v1.RPBottomNavBar)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.items_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.background_color_ != nullptr);
      _impl_.background_color_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.selected_color_ != nullptr);
      _impl_.selected_color_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(_impl_.unselected_color_ != nullptr);
      _impl_.unselected_color_->Clear();
    }
  }
  _impl_.selected_index_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RPBottomNavBar::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RPBottomNavBar& this_ = static_cast<const RPBottomNavBar&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RPBottomNavBar::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RPBottomNavBar& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.renderprotocol.ui.v1.RPBottomNavBar)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_items_size());
         i < n; i++) {
      const auto& repfield = this_._internal_items().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // optional int32 selected_index = 2 [json_name = "selectedIndex"];
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
            stream, this_._internal_selected_index(), target);
  }

  // optional .proto.renderprotocol.ui.v1.RPColor background_color = 3 [json_name = "backgroundColor"];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.background_color_, this_._impl_.background_color_->GetCachedSize(), target,
        stream);
  }

  // optional .proto.renderprotocol.ui.v1.RPColor selected_color = 4 [json_name = "selectedColor"];
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *this_._impl_.selected_color_, this_._impl_.selected_color_->GetCachedSize(), target,
        stream);
  }

  // optional .proto.renderprotocol.ui.v1.RPColor unselected_color = 5 [json_name = "unselectedColor"];
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        5, *this_._impl_.unselected_color_, this_._impl_.unselected_color_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.renderprotocol.ui.v1.RPBottomNavBar)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RPBottomNavBar::ByteSizeLong(const MessageLite& base) {
  const RPBottomNavBar& this_ = static_cast<const RPBottomNavBar&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RPBottomNavBar::ByteSizeLong() const {
  const RPBottomNavBar& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.renderprotocol.ui.v1.RPBottomNavBar)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // repeated .proto.renderprotocol.ui.v1.RPBottomNavItem items = 1 [json_name = "items"];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_items_size();
      for (const auto& msg : this_._internal_items()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // optional .proto.renderprotocol.ui.v1.RPColor background_color = 3 [json_name = "backgroundColor"];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.background_color_);
    }
    // optional .proto.renderprotocol.ui.v1.RPColor selected_color = 4 [json_name = "selectedColor"];
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.selected_color_);
    }
    // optional .proto.renderprotocol.ui.v1.RPColor unselected_color = 5 [json_name = "unselectedColor"];
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.unselected_color_);
    }
    // optional int32 selected_index = 2 [json_name = "selectedIndex"];
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_selected_index());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RPBottomNavBar::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<RPBottomNavBar*>(&to_msg);
  auto& from = static_cast<const RPBottomNavBar&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.renderprotocol.ui.v1.RPBottomNavBar)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_items()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_items());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.background_color_ != nullptr);
      if (_this->_impl_.background_color_ == nullptr) {
        _this->_impl_.background_color_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.background_color_);
      } else {
        _this->_impl_.background_color_->MergeFrom(*from._impl_.background_color_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.selected_color_ != nullptr);
      if (_this->_impl_.selected_color_ == nullptr) {
        _this->_impl_.selected_color_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.selected_color_);
      } else {
        _this->_impl_.selected_color_->MergeFrom(*from._impl_.selected_color_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(from._impl_.unselected_color_ != nullptr);
      if (_this->_impl_.unselected_color_ == nullptr) {
        _this->_impl_.unselected_color_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.unselected_color_);
      } else {
        _this->_impl_.unselected_color_->MergeFrom(*from._impl_.unselected_color_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.selected_index_ = from._impl_.selected_index_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void RPBottomNavBar::CopyFrom(const RPBottomNavBar& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.renderprotocol.ui.v1.RPBottomNavBar)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RPBottomNavBar::InternalSwap(RPBottomNavBar* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.items_.InternalSwap(&other->_impl_.items_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RPBottomNavBar, _impl_.selected_index_)
      + sizeof(RPBottomNavBar::_impl_.selected_index_)
      - PROTOBUF_FIELD_OFFSET(RPBottomNavBar, _impl_.background_color_)>(
          reinterpret_cast<char*>(&_impl_.background_color_),
          reinterpret_cast<char*>(&other->_impl_.background_color_));
}

::google::protobuf::Metadata RPBottomNavBar::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

void RPBottomNavItem::clear_icon() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.icon_ != nullptr) _impl_.icon_->Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
void RPBottomNavItem::clear_action() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.action_ != nullptr) _impl_.action_->Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
RPBottomNavItem::RPBottomNavItem(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RPBottomNavItem_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.renderprotocol.ui.v1.RPBottomNavItem)
}
PROTOBUF_NDEBUG_INLINE RPBottomNavItem::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::renderprotocol::ui::v1::RPBottomNavItem& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        label_(arena, from.label_) {}

RPBottomNavItem::RPBottomNavItem(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RPBottomNavItem& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RPBottomNavItem_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RPBottomNavItem* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.icon_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.icon_)
                : nullptr;
  _impl_.action_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.action_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:proto.renderprotocol.ui.v1.RPBottomNavItem)
}
PROTOBUF_NDEBUG_INLINE RPBottomNavItem::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        label_(arena) {}

inline void RPBottomNavItem::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, icon_),
           0,
           offsetof(Impl_, action_) -
               offsetof(Impl_, icon_) +
               sizeof(Impl_::action_));
}
RPBottomNavItem::~RPBottomNavItem() {
  // @@protoc_insertion_point(destructor:proto.renderprotocol.ui.v1.RPBottomNavItem)
  SharedDtor(*this);
}
inline void RPBottomNavItem::SharedDtor(MessageLite& self) {
  RPBottomNavItem& this_ = static_cast<RPBottomNavItem&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.label_.Destroy();
  delete this_._impl_.icon_;
  delete this_._impl_.action_;
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RPBottomNavItem_class_data_ =
        RPBottomNavItem::InternalGenerateClassData_(RPBottomNavItem_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RPBottomNavItem::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RPBottomNavItem_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RPBottomNavItem_class_data_.tc_table);
  return RPBottomNavItem_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RPBottomNavItem::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RPBottomNavItem_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&RPBottomNavItem_globals_));
  return RPBottomNavItem_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const RPBottomNavItem::ParseTableT_
    RPBottomNavItem::_table_ =
        RPBottomNavItem::InternalGenerateParseTable_(RPBottomNavItem_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void RPBottomNavItem::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.renderprotocol.ui.v1.RPBottomNavItem)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.label_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.icon_ != nullptr);
      _impl_.icon_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.action_ != nullptr);
      _impl_.action_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RPBottomNavItem::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RPBottomNavItem& this_ = static_cast<const RPBottomNavItem&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RPBottomNavItem::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RPBottomNavItem& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.renderprotocol.ui.v1.RPBottomNavItem)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .proto.renderprotocol.ui.v1.RPIcon icon = 1 [json_name = "icon"];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.icon_, this_._impl_.icon_->GetCachedSize(), target,
        stream);
  }

  // optional string label = 2 [json_name = "label"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_label();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.renderprotocol.ui.v1.RPBottomNavItem.label");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // .proto.renderprotocol.ui.v1.RPAction action = 3 [json_name = "action"];
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.action_, this_._impl_.action_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.renderprotocol.ui.v1.RPBottomNavItem)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RPBottomNavItem::ByteSizeLong(const MessageLite& base) {
  const RPBottomNavItem& this_ = static_cast<const RPBottomNavItem&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RPBottomNavItem::ByteSizeLong() const {
  const RPBottomNavItem& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.renderprotocol.ui.v1.RPBottomNavItem)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // optional string label = 2 [json_name = "label"];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_label());
    }
    // .proto.renderprotocol.ui.v1.RPIcon icon = 1 [json_name = "icon"];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.icon_);
    }
    // .proto.renderprotocol.ui.v1.RPAction action = 3 [json_name = "action"];
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.action_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RPBottomNavItem::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<RPBottomNavItem*>(&to_msg);
  auto& from = static_cast<const RPBottomNavItem&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.renderprotocol.ui.v1.RPBottomNavItem)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_label(from._internal_label());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.icon_ != nullptr);
      if (_this->_impl_.icon_ == nullptr) {
        _this->_impl_.icon_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.icon_);
      } else {
        _this->_impl_.icon_->MergeFrom(*from._impl_.icon_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.action_ != nullptr);
      if (_this->_impl_.action_ == nullptr) {
        _this->_impl_.action_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.action_);
      } else {
        _this->_impl_.action_->MergeFrom(*from._impl_.action_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void RPBottomNavItem::CopyFrom(const RPBottomNavItem& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.renderprotocol.ui.v1.RPBottomNavItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RPBottomNavItem::InternalSwap(RPBottomNavItem* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.label_, &other->_impl_.label_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RPBottomNavItem, _impl_.action_)
      + sizeof(RPBottomNavItem::_impl_.action_)
      - PROTOBUF_FIELD_OFFSET(RPBottomNavItem, _impl_.icon_)>(
          reinterpret_cast<char*>(&_impl_.icon_),
          reinterpret_cast<char*>(&other->_impl_.icon_));
}

::google::protobuf::Metadata RPBottomNavItem::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace ui
}  // namespace renderprotocol
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fbottom_5fnav_5fbar_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
