// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/ui/v1/rp_ui_icon.proto
// Protobuf C++ Version: 7.35.0

#include "proto/renderprotocol/ui/v1/rp_ui_icon.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::proto::renderprotocol::ui::v1::RPIcon
        {&::_pbi::kDescriptorMethods, &::descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ficon_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
namespace proto {
namespace renderprotocol {
namespace ui {
namespace v1 {
class RPIcon::_Internal {
 public:
  using HasBits = decltype(::std::declval<RPIcon>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RPIcon, _impl_._has_bits_);
};

constexpr RPIcon::ParseTableT_ RPIcon::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(RPIcon, _impl_._has_bits_),
      0, // no _extensions_
      3, 24,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967288,  // skipmap
      offsetof(ParseTableT_, field_entries),
      3,  // num_field_entries
      1,  // num_aux_entries
      offsetof(ParseTableT_, aux_entries),
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::proto::renderprotocol::ui::v1::RPIcon>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
      // string name = 1 [json_name = "name"];
      {::_pbi::TcParser::FastUS1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(RPIcon, _impl_.name_)}},
      // optional float size = 2 [json_name = "size"];
      {::_pbi::TcParser::FastF32S1,
       {21, 2, 0,
        PROTOBUF_FIELD_OFFSET(RPIcon, _impl_.size_)}},
      // optional .proto.renderprotocol.ui.v1.RPColor color = 3 [json_name = "color"];
      {::_pbi::TcParser::FastMtS1,
       {26, 1, 0,
        PROTOBUF_FIELD_OFFSET(RPIcon, _impl_.color_)}},
    }}, {{
      65535, 65535
    }}, {{
      // string name = 1 [json_name = "name"];
      {PROTOBUF_FIELD_OFFSET(RPIcon, _impl_.name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // optional float size = 2 [json_name = "size"];
      {PROTOBUF_FIELD_OFFSET(RPIcon, _impl_.size_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
      // optional .proto.renderprotocol.ui.v1.RPColor color = 3 [json_name = "color"];
      {PROTOBUF_FIELD_OFFSET(RPIcon, _impl_.color_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    }},
    {{
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::proto::renderprotocol::ui::v1::RPColor>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::proto::renderprotocol::ui::v1::RPColor_globals_},
        #endif
    }},
    {{
      "\41\4\0\0\0\0\0\0"
      "proto.renderprotocol.ui.v1.RPIcon"
      "name"
    }},
  };
}


inline constexpr RPIcon::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        color_{nullptr},
        size_{0} {}

template <typename>
constexpr RPIcon::RPIcon(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL RPIcon::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RPIcon(arena);
}
constexpr auto RPIcon::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RPIcon), alignof(RPIcon));
}
constexpr auto RPIcon::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &RPIcon::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RPIcon>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RPIcon::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RPIcon>(), &RPIcon::ByteSizeLong,
              &RPIcon::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RPIcon, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ficon_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct RPIconGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr RPIconGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 RPIcon_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(RPIcon::InternalGenerateClassData_(
            _default, &RPIcon_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<RPIcon>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~RPIconGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) RPIcon _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<RPIcon>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(RPIconGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST RPIconGlobalsTypeInternal RPIcon_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* RPIcon_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return RPIcon_globals_.GetClassData();
#else
  return RPIcon_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
}  // namespace v1
}  // namespace ui
}  // namespace renderprotocol
}  // namespace proto
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ficon_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ficon_2eproto = nullptr;
const ::uint32_t
    TableStruct_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ficon_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPIcon, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPIcon, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPIcon, _impl_.size_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::ui::v1::RPIcon, _impl_.color_),
        0,
        2,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::proto::renderprotocol::ui::v1::RPIcon)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::proto::renderprotocol::ui::v1::RPIcon_globals_,
};
const char descriptor_table_protodef_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ficon_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n+proto/renderprotocol/ui/v1/rp_ui_icon."
    "proto\022\032proto.renderprotocol.ui.v1\032,proto"
    "/renderprotocol/ui/v1/rp_ui_color.proto\""
    "\210\001\n\006RPIcon\022\022\n\004name\030\001 \001(\tR\004name\022\027\n\004size\030\002"
    " \001(\002H\000R\004size\210\001\001\022>\n\005color\030\003 \001(\0132#.proto.r"
    "enderprotocol.ui.v1.RPColorH\001R\005color\210\001\001B"
    "\007\n\005_sizeB\010\n\006_colorB\302\001\n\036com.proto.renderp"
    "rotocol.ui.v1B\rRpUiIconProtoH\001P\001\370\001\001\242\002\003PR"
    "U\252\002\032Proto.Renderprotocol.Ui.V1\272\002\000\312\002\032Prot"
    "o\\Renderprotocol\\Ui\\V1\342\002&Proto\\Renderpro"
    "tocol\\Ui\\V1\\GPBMetadata\352\002\035Proto::Renderp"
    "rotocol::Ui::V1b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ficon_2eproto_deps[1] = {
        &::descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fcolor_2eproto,
};
static ::absl::once_flag descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ficon_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ficon_2eproto = {
    false,
    false,
    463,
    descriptor_table_protodef_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ficon_2eproto,
    "proto/renderprotocol/ui/v1/rp_ui_icon.proto",
    &descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ficon_2eproto_once,
    descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ficon_2eproto_deps,
    1,
    1,
    schemas,
    file_message_globals,
    TableStruct_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ficon_2eproto::offsets,
    file_level_enum_descriptors_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ficon_2eproto,
    file_level_service_descriptors_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ficon_2eproto,
};
namespace proto {
namespace renderprotocol {
namespace ui {
namespace v1 {
// ===================================================================

void RPIcon::clear_color() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.color_ != nullptr) _impl_.color_->Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
RPIcon::RPIcon(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RPIcon_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.renderprotocol.ui.v1.RPIcon)
}
PROTOBUF_NDEBUG_INLINE RPIcon::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::renderprotocol::ui::v1::RPIcon& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

RPIcon::RPIcon(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RPIcon& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RPIcon_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RPIcon* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.color_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.color_)
                : nullptr;
  _impl_.size_ = from._impl_.size_;

  // @@protoc_insertion_point(copy_constructor:proto.renderprotocol.ui.v1.RPIcon)
}
PROTOBUF_NDEBUG_INLINE RPIcon::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        name_(arena) {}

inline void RPIcon::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, color_),
           0,
           offsetof(Impl_, size_) -
               offsetof(Impl_, color_) +
               sizeof(Impl_::size_));
}
RPIcon::~RPIcon() {
  // @@protoc_insertion_point(destructor:proto.renderprotocol.ui.v1.RPIcon)
  SharedDtor(*this);
}
inline void RPIcon::SharedDtor(MessageLite& self) {
  RPIcon& this_ = static_cast<RPIcon&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  delete this_._impl_.color_;
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RPIcon_class_data_ =
        RPIcon::InternalGenerateClassData_(RPIcon_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RPIcon::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RPIcon_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RPIcon_class_data_.tc_table);
  return RPIcon_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RPIcon::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RPIcon_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&RPIcon_globals_));
  return RPIcon_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const RPIcon::ParseTableT_
    RPIcon::_table_ =
        RPIcon::InternalGenerateParseTable_(RPIcon_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void RPIcon::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.renderprotocol.ui.v1.RPIcon)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.color_ != nullptr);
      _impl_.color_->Clear();
    }
  }
  _impl_.size_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RPIcon::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RPIcon& this_ = static_cast<const RPIcon&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RPIcon::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RPIcon& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.renderprotocol.ui.v1.RPIcon)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string name = 1 [json_name = "name"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_name().empty()) {
      const ::std::string& _s = this_._internal_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.renderprotocol.ui.v1.RPIcon.name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // optional float size = 2 [json_name = "size"];
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        2, this_._internal_size(), target);
  }

  // optional .proto.renderprotocol.ui.v1.RPColor color = 3 [json_name = "color"];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.color_, this_._impl_.color_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.renderprotocol.ui.v1.RPIcon)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RPIcon::ByteSizeLong(const MessageLite& base) {
  const RPIcon& this_ = static_cast<const RPIcon&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RPIcon::ByteSizeLong() const {
  const RPIcon& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.renderprotocol.ui.v1.RPIcon)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000004U & cached_has_bits) * 5;
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string name = 1 [json_name = "name"];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_name());
      }
    }
    // optional .proto.renderprotocol.ui.v1.RPColor color = 3 [json_name = "color"];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.color_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RPIcon::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<RPIcon*>(&to_msg);
  auto& from = static_cast<const RPIcon&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.renderprotocol.ui.v1.RPIcon)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_name().empty()) {
        _this->_internal_set_name(from._internal_name());
      } else {
        if (_this->_impl_.name_.IsDefault()) {
          _this->_internal_set_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.color_ != nullptr);
      if (_this->_impl_.color_ == nullptr) {
        _this->_impl_.color_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.color_);
      } else {
        _this->_impl_.color_->MergeFrom(*from._impl_.color_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.size_ = from._impl_.size_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void RPIcon::CopyFrom(const RPIcon& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.renderprotocol.ui.v1.RPIcon)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RPIcon::InternalSwap(RPIcon* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RPIcon, _impl_.size_)
      + sizeof(RPIcon::_impl_.size_)
      - PROTOBUF_FIELD_OFFSET(RPIcon, _impl_.color_)>(
          reinterpret_cast<char*>(&_impl_.color_),
          reinterpret_cast<char*>(&other->_impl_.color_));
}

::google::protobuf::Metadata RPIcon::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace ui
}  // namespace renderprotocol
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5ficon_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
