// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/api/v1/rp_api_render_service.proto
// Protobuf C++ Version: 6.33.5

#include "proto/renderprotocol/api/v1/rp_api_render_service.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace proto {
namespace renderprotocol {
namespace api {
namespace v1 {

inline constexpr RPFetchRenderTreeRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        session_token_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        view_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR RPFetchRenderTreeRequest::RPFetchRenderTreeRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RPFetchRenderTreeRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RPFetchRenderTreeRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RPFetchRenderTreeRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RPFetchRenderTreeRequestDefaultTypeInternal() {}
  union {
    RPFetchRenderTreeRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RPFetchRenderTreeRequestDefaultTypeInternal _RPFetchRenderTreeRequest_default_instance_;

inline constexpr RPFetchRenderTreeResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        view_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR RPFetchRenderTreeResponse::RPFetchRenderTreeResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RPFetchRenderTreeResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RPFetchRenderTreeResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RPFetchRenderTreeResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RPFetchRenderTreeResponseDefaultTypeInternal() {}
  union {
    RPFetchRenderTreeResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RPFetchRenderTreeResponseDefaultTypeInternal _RPFetchRenderTreeResponse_default_instance_;
}  // namespace v1
}  // namespace api
}  // namespace renderprotocol
}  // namespace proto
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5frender_5fservice_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5frender_5fservice_2eproto = nullptr;
const ::uint32_t
    TableStruct_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5frender_5fservice_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::api::v1::RPFetchRenderTreeRequest, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::api::v1::RPFetchRenderTreeRequest, _impl_.session_token_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::api::v1::RPFetchRenderTreeRequest, _impl_.view_id_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::api::v1::RPFetchRenderTreeResponse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::api::v1::RPFetchRenderTreeResponse, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::proto::renderprotocol::api::v1::RPFetchRenderTreeResponse, _impl_.view_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::proto::renderprotocol::api::v1::RPFetchRenderTreeRequest)},
        {7, sizeof(::proto::renderprotocol::api::v1::RPFetchRenderTreeResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::proto::renderprotocol::api::v1::_RPFetchRenderTreeRequest_default_instance_._instance,
    &::proto::renderprotocol::api::v1::_RPFetchRenderTreeResponse_default_instance_._instance,
};
const char descriptor_table_protodef_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5frender_5fservice_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n7proto/renderprotocol/api/v1/rp_api_ren"
    "der_service.proto\022\033proto.renderprotocol."
    "api.v1\032+proto/renderprotocol/ui/v1/rp_ui"
    "_core.proto\"X\n\030RPFetchRenderTreeRequest\022"
    "#\n\rsession_token\030\001 \001(\tR\014sessionToken\022\027\n\007"
    "view_id\030\002 \001(\tR\006viewId\"e\n\031RPFetchRenderTr"
    "eeResponse\022\016\n\002id\030\001 \001(\tR\002id\0228\n\004view\030\002 \001(\013"
    "2$.proto.renderprotocol.ui.v1.RPWidgetR\004"
    "view2\226\001\n\017RPRenderService\022\202\001\n\021RPFetchRend"
    "erTree\0225.proto.renderprotocol.api.v1.RPF"
    "etchRenderTreeRequest\0326.proto.renderprot"
    "ocol.api.v1.RPFetchRenderTreeResponseB\321\001"
    "\n\037com.proto.renderprotocol.api.v1B\027RpApi"
    "RenderServiceProtoH\001P\001\370\001\001\242\002\003PRA\252\002\033Proto."
    "Renderprotocol.Api.V1\272\002\000\312\002\033Proto\\Renderp"
    "rotocol\\Api\\V1\342\002\'Proto\\Renderprotocol\\Ap"
    "i\\V1\\GPBMetadata\352\002\036Proto::Renderprotocol"
    "::Api::V1b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5frender_5fservice_2eproto_deps[1] = {
        &::descriptor_table_proto_2frenderprotocol_2fui_2fv1_2frp_5fui_5fcore_2eproto,
};
static ::absl::once_flag descriptor_table_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5frender_5fservice_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5frender_5fservice_2eproto = {
    false,
    false,
    697,
    descriptor_table_protodef_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5frender_5fservice_2eproto,
    "proto/renderprotocol/api/v1/rp_api_render_service.proto",
    &descriptor_table_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5frender_5fservice_2eproto_once,
    descriptor_table_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5frender_5fservice_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5frender_5fservice_2eproto::offsets,
    file_level_enum_descriptors_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5frender_5fservice_2eproto,
    file_level_service_descriptors_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5frender_5fservice_2eproto,
};
namespace proto {
namespace renderprotocol {
namespace api {
namespace v1 {
// ===================================================================

class RPFetchRenderTreeRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RPFetchRenderTreeRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RPFetchRenderTreeRequest, _impl_._has_bits_);
};

RPFetchRenderTreeRequest::RPFetchRenderTreeRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RPFetchRenderTreeRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.renderprotocol.api.v1.RPFetchRenderTreeRequest)
}
PROTOBUF_NDEBUG_INLINE RPFetchRenderTreeRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::renderprotocol::api::v1::RPFetchRenderTreeRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        session_token_(arena, from.session_token_),
        view_id_(arena, from.view_id_) {}

RPFetchRenderTreeRequest::RPFetchRenderTreeRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RPFetchRenderTreeRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RPFetchRenderTreeRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RPFetchRenderTreeRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:proto.renderprotocol.api.v1.RPFetchRenderTreeRequest)
}
PROTOBUF_NDEBUG_INLINE RPFetchRenderTreeRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        session_token_(arena),
        view_id_(arena) {}

inline void RPFetchRenderTreeRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RPFetchRenderTreeRequest::~RPFetchRenderTreeRequest() {
  // @@protoc_insertion_point(destructor:proto.renderprotocol.api.v1.RPFetchRenderTreeRequest)
  SharedDtor(*this);
}
inline void RPFetchRenderTreeRequest::SharedDtor(MessageLite& self) {
  RPFetchRenderTreeRequest& this_ = static_cast<RPFetchRenderTreeRequest&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.session_token_.Destroy();
  this_._impl_.view_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RPFetchRenderTreeRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RPFetchRenderTreeRequest(arena);
}
constexpr auto RPFetchRenderTreeRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RPFetchRenderTreeRequest),
                                            alignof(RPFetchRenderTreeRequest));
}
constexpr auto RPFetchRenderTreeRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RPFetchRenderTreeRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RPFetchRenderTreeRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RPFetchRenderTreeRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RPFetchRenderTreeRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RPFetchRenderTreeRequest>(), &RPFetchRenderTreeRequest::ByteSizeLong,
              &RPFetchRenderTreeRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RPFetchRenderTreeRequest, _impl_._cached_size_),
          false,
      },
      &RPFetchRenderTreeRequest::kDescriptorMethods,
      &descriptor_table_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5frender_5fservice_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RPFetchRenderTreeRequest_class_data_ =
        RPFetchRenderTreeRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RPFetchRenderTreeRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RPFetchRenderTreeRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RPFetchRenderTreeRequest_class_data_.tc_table);
  return RPFetchRenderTreeRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 81, 2>
RPFetchRenderTreeRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RPFetchRenderTreeRequest, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RPFetchRenderTreeRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::renderprotocol::api::v1::RPFetchRenderTreeRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string view_id = 2 [json_name = "viewId"];
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(RPFetchRenderTreeRequest, _impl_.view_id_)}},
    // string session_token = 1 [json_name = "sessionToken"];
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(RPFetchRenderTreeRequest, _impl_.session_token_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string session_token = 1 [json_name = "sessionToken"];
    {PROTOBUF_FIELD_OFFSET(RPFetchRenderTreeRequest, _impl_.session_token_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string view_id = 2 [json_name = "viewId"];
    {PROTOBUF_FIELD_OFFSET(RPFetchRenderTreeRequest, _impl_.view_id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\64\15\7\0\0\0\0\0"
    "proto.renderprotocol.api.v1.RPFetchRenderTreeRequest"
    "session_token"
    "view_id"
  }},
};
PROTOBUF_NOINLINE void RPFetchRenderTreeRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.renderprotocol.api.v1.RPFetchRenderTreeRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.session_token_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.view_id_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RPFetchRenderTreeRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RPFetchRenderTreeRequest& this_ = static_cast<const RPFetchRenderTreeRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RPFetchRenderTreeRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RPFetchRenderTreeRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.renderprotocol.api.v1.RPFetchRenderTreeRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string session_token = 1 [json_name = "sessionToken"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_session_token().empty()) {
      const ::std::string& _s = this_._internal_session_token();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.renderprotocol.api.v1.RPFetchRenderTreeRequest.session_token");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string view_id = 2 [json_name = "viewId"];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_view_id().empty()) {
      const ::std::string& _s = this_._internal_view_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.renderprotocol.api.v1.RPFetchRenderTreeRequest.view_id");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.renderprotocol.api.v1.RPFetchRenderTreeRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RPFetchRenderTreeRequest::ByteSizeLong(const MessageLite& base) {
  const RPFetchRenderTreeRequest& this_ = static_cast<const RPFetchRenderTreeRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RPFetchRenderTreeRequest::ByteSizeLong() const {
  const RPFetchRenderTreeRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.renderprotocol.api.v1.RPFetchRenderTreeRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string session_token = 1 [json_name = "sessionToken"];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_session_token().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_session_token());
      }
    }
    // string view_id = 2 [json_name = "viewId"];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_view_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_view_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RPFetchRenderTreeRequest::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<RPFetchRenderTreeRequest*>(&to_msg);
  auto& from = static_cast<const RPFetchRenderTreeRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.renderprotocol.api.v1.RPFetchRenderTreeRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_session_token().empty()) {
        _this->_internal_set_session_token(from._internal_session_token());
      } else {
        if (_this->_impl_.session_token_.IsDefault()) {
          _this->_internal_set_session_token("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_view_id().empty()) {
        _this->_internal_set_view_id(from._internal_view_id());
      } else {
        if (_this->_impl_.view_id_.IsDefault()) {
          _this->_internal_set_view_id("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void RPFetchRenderTreeRequest::CopyFrom(const RPFetchRenderTreeRequest& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.renderprotocol.api.v1.RPFetchRenderTreeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RPFetchRenderTreeRequest::InternalSwap(RPFetchRenderTreeRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.session_token_, &other->_impl_.session_token_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.view_id_, &other->_impl_.view_id_, arena);
}

::google::protobuf::Metadata RPFetchRenderTreeRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RPFetchRenderTreeResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RPFetchRenderTreeResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RPFetchRenderTreeResponse, _impl_._has_bits_);
};

void RPFetchRenderTreeResponse::clear_view() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.view_ != nullptr) _impl_.view_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
RPFetchRenderTreeResponse::RPFetchRenderTreeResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RPFetchRenderTreeResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.renderprotocol.api.v1.RPFetchRenderTreeResponse)
}
PROTOBUF_NDEBUG_INLINE RPFetchRenderTreeResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::renderprotocol::api::v1::RPFetchRenderTreeResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        id_(arena, from.id_) {}

RPFetchRenderTreeResponse::RPFetchRenderTreeResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RPFetchRenderTreeResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RPFetchRenderTreeResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RPFetchRenderTreeResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.view_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.view_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:proto.renderprotocol.api.v1.RPFetchRenderTreeResponse)
}
PROTOBUF_NDEBUG_INLINE RPFetchRenderTreeResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        id_(arena) {}

inline void RPFetchRenderTreeResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.view_ = {};
}
RPFetchRenderTreeResponse::~RPFetchRenderTreeResponse() {
  // @@protoc_insertion_point(destructor:proto.renderprotocol.api.v1.RPFetchRenderTreeResponse)
  SharedDtor(*this);
}
inline void RPFetchRenderTreeResponse::SharedDtor(MessageLite& self) {
  RPFetchRenderTreeResponse& this_ = static_cast<RPFetchRenderTreeResponse&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.id_.Destroy();
  delete this_._impl_.view_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RPFetchRenderTreeResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RPFetchRenderTreeResponse(arena);
}
constexpr auto RPFetchRenderTreeResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RPFetchRenderTreeResponse),
                                            alignof(RPFetchRenderTreeResponse));
}
constexpr auto RPFetchRenderTreeResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RPFetchRenderTreeResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RPFetchRenderTreeResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RPFetchRenderTreeResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RPFetchRenderTreeResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RPFetchRenderTreeResponse>(), &RPFetchRenderTreeResponse::ByteSizeLong,
              &RPFetchRenderTreeResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RPFetchRenderTreeResponse, _impl_._cached_size_),
          false,
      },
      &RPFetchRenderTreeResponse::kDescriptorMethods,
      &descriptor_table_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5frender_5fservice_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RPFetchRenderTreeResponse_class_data_ =
        RPFetchRenderTreeResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RPFetchRenderTreeResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RPFetchRenderTreeResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RPFetchRenderTreeResponse_class_data_.tc_table);
  return RPFetchRenderTreeResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 64, 2>
RPFetchRenderTreeResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RPFetchRenderTreeResponse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    RPFetchRenderTreeResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::renderprotocol::api::v1::RPFetchRenderTreeResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .proto.renderprotocol.ui.v1.RPWidget view = 2 [json_name = "view"];
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(RPFetchRenderTreeResponse, _impl_.view_)}},
    // string id = 1 [json_name = "id"];
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(RPFetchRenderTreeResponse, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string id = 1 [json_name = "id"];
    {PROTOBUF_FIELD_OFFSET(RPFetchRenderTreeResponse, _impl_.id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .proto.renderprotocol.ui.v1.RPWidget view = 2 [json_name = "view"];
    {PROTOBUF_FIELD_OFFSET(RPFetchRenderTreeResponse, _impl_.view_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::proto::renderprotocol::ui::v1::RPWidget>()},
  }},
  {{
    "\65\2\0\0\0\0\0\0"
    "proto.renderprotocol.api.v1.RPFetchRenderTreeResponse"
    "id"
  }},
};
PROTOBUF_NOINLINE void RPFetchRenderTreeResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.renderprotocol.api.v1.RPFetchRenderTreeResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.id_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.view_ != nullptr);
      _impl_.view_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RPFetchRenderTreeResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RPFetchRenderTreeResponse& this_ = static_cast<const RPFetchRenderTreeResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RPFetchRenderTreeResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RPFetchRenderTreeResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.renderprotocol.api.v1.RPFetchRenderTreeResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string id = 1 [json_name = "id"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_id().empty()) {
      const ::std::string& _s = this_._internal_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.renderprotocol.api.v1.RPFetchRenderTreeResponse.id");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // .proto.renderprotocol.ui.v1.RPWidget view = 2 [json_name = "view"];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.view_, this_._impl_.view_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.renderprotocol.api.v1.RPFetchRenderTreeResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RPFetchRenderTreeResponse::ByteSizeLong(const MessageLite& base) {
  const RPFetchRenderTreeResponse& this_ = static_cast<const RPFetchRenderTreeResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RPFetchRenderTreeResponse::ByteSizeLong() const {
  const RPFetchRenderTreeResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.renderprotocol.api.v1.RPFetchRenderTreeResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string id = 1 [json_name = "id"];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_id());
      }
    }
    // .proto.renderprotocol.ui.v1.RPWidget view = 2 [json_name = "view"];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.view_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RPFetchRenderTreeResponse::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<RPFetchRenderTreeResponse*>(&to_msg);
  auto& from = static_cast<const RPFetchRenderTreeResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.renderprotocol.api.v1.RPFetchRenderTreeResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_id().empty()) {
        _this->_internal_set_id(from._internal_id());
      } else {
        if (_this->_impl_.id_.IsDefault()) {
          _this->_internal_set_id("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.view_ != nullptr);
      if (_this->_impl_.view_ == nullptr) {
        _this->_impl_.view_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.view_);
      } else {
        _this->_impl_.view_->MergeFrom(*from._impl_.view_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void RPFetchRenderTreeResponse::CopyFrom(const RPFetchRenderTreeResponse& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.renderprotocol.api.v1.RPFetchRenderTreeResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RPFetchRenderTreeResponse::InternalSwap(RPFetchRenderTreeResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
  swap(_impl_.view_, other->_impl_.view_);
}

::google::protobuf::Metadata RPFetchRenderTreeResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace api
}  // namespace renderprotocol
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5frender_5fservice_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
