// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/api/v1/rp_api_metadata.proto
// Protobuf C++ Version: 6.33.5

#ifndef proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5fmetadata_2eproto_2epb_2eh
#define proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5fmetadata_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "proto/renderprotocol/api/v1/rp_api_platform.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5fmetadata_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5fmetadata_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5fmetadata_2eproto;
}  // extern "C"
namespace proto {
namespace renderprotocol {
namespace api {
namespace v1 {
class RPApiMetadata;
struct RPApiMetadataDefaultTypeInternal;
extern RPApiMetadataDefaultTypeInternal _RPApiMetadata_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RPApiMetadata_class_data_;
class RPAppMetadata;
struct RPAppMetadataDefaultTypeInternal;
extern RPAppMetadataDefaultTypeInternal _RPAppMetadata_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RPAppMetadata_class_data_;
class RPDeviceMetadata;
struct RPDeviceMetadataDefaultTypeInternal;
extern RPDeviceMetadataDefaultTypeInternal _RPDeviceMetadata_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RPDeviceMetadata_class_data_;
}  // namespace v1
}  // namespace api
}  // namespace renderprotocol
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace proto {
namespace renderprotocol {
namespace api {
namespace v1 {

// ===================================================================


// -------------------------------------------------------------------

class RPDeviceMetadata final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.renderprotocol.api.v1.RPDeviceMetadata) */ {
 public:
  inline RPDeviceMetadata() : RPDeviceMetadata(nullptr) {}
  ~RPDeviceMetadata() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RPDeviceMetadata* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RPDeviceMetadata));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RPDeviceMetadata(::google::protobuf::internal::ConstantInitialized);

  inline RPDeviceMetadata(const RPDeviceMetadata& from) : RPDeviceMetadata(nullptr, from) {}
  inline RPDeviceMetadata(RPDeviceMetadata&& from) noexcept
      : RPDeviceMetadata(nullptr, ::std::move(from)) {}
  inline RPDeviceMetadata& operator=(const RPDeviceMetadata& from) {
    CopyFrom(from);
    return *this;
  }
  inline RPDeviceMetadata& operator=(RPDeviceMetadata&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RPDeviceMetadata& default_instance() {
    return *reinterpret_cast<const RPDeviceMetadata*>(
        &_RPDeviceMetadata_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(RPDeviceMetadata& a, RPDeviceMetadata& b) { a.Swap(&b); }
  inline void Swap(RPDeviceMetadata* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RPDeviceMetadata* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RPDeviceMetadata* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RPDeviceMetadata>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RPDeviceMetadata& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RPDeviceMetadata& from) { RPDeviceMetadata::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RPDeviceMetadata* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.renderprotocol.api.v1.RPDeviceMetadata"; }

  explicit RPDeviceMetadata(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RPDeviceMetadata(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RPDeviceMetadata& from);
  RPDeviceMetadata(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RPDeviceMetadata&& from) noexcept
      : RPDeviceMetadata(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDeviceModelFieldNumber = 1,
    kOsVersionFieldNumber = 2,
    kPlatformFieldNumber = 3,
  };
  // string device_model = 1 [json_name = "deviceModel"];
  void clear_device_model() ;
  const ::std::string& device_model() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_device_model(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_device_model();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_device_model();
  void set_allocated_device_model(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_device_model() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_device_model(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_device_model();

  public:
  // string os_version = 2 [json_name = "osVersion"];
  void clear_os_version() ;
  const ::std::string& os_version() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_os_version(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_os_version();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_os_version();
  void set_allocated_os_version(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_os_version() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_os_version(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_os_version();

  public:
  // .proto.renderprotocol.api.v1.RPPlatform platform = 3 [json_name = "platform"];
  void clear_platform() ;
  ::proto::renderprotocol::api::v1::RPPlatform platform() const;
  void set_platform(::proto::renderprotocol::api::v1::RPPlatform value);

  private:
  ::proto::renderprotocol::api::v1::RPPlatform _internal_platform() const;
  void _internal_set_platform(::proto::renderprotocol::api::v1::RPPlatform value);

  public:
  // @@protoc_insertion_point(class_scope:proto.renderprotocol.api.v1.RPDeviceMetadata)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 75,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RPDeviceMetadata& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr device_model_;
    ::google::protobuf::internal::ArenaStringPtr os_version_;
    int platform_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5fmetadata_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RPDeviceMetadata_class_data_;
// -------------------------------------------------------------------

class RPAppMetadata final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.renderprotocol.api.v1.RPAppMetadata) */ {
 public:
  inline RPAppMetadata() : RPAppMetadata(nullptr) {}
  ~RPAppMetadata() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RPAppMetadata* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RPAppMetadata));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RPAppMetadata(::google::protobuf::internal::ConstantInitialized);

  inline RPAppMetadata(const RPAppMetadata& from) : RPAppMetadata(nullptr, from) {}
  inline RPAppMetadata(RPAppMetadata&& from) noexcept
      : RPAppMetadata(nullptr, ::std::move(from)) {}
  inline RPAppMetadata& operator=(const RPAppMetadata& from) {
    CopyFrom(from);
    return *this;
  }
  inline RPAppMetadata& operator=(RPAppMetadata&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RPAppMetadata& default_instance() {
    return *reinterpret_cast<const RPAppMetadata*>(
        &_RPAppMetadata_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(RPAppMetadata& a, RPAppMetadata& b) { a.Swap(&b); }
  inline void Swap(RPAppMetadata* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RPAppMetadata* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RPAppMetadata* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RPAppMetadata>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RPAppMetadata& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RPAppMetadata& from) { RPAppMetadata::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RPAppMetadata* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.renderprotocol.api.v1.RPAppMetadata"; }

  explicit RPAppMetadata(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RPAppMetadata(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RPAppMetadata& from);
  RPAppMetadata(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RPAppMetadata&& from) noexcept
      : RPAppMetadata(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBundleIdFieldNumber = 1,
    kAppVersionFieldNumber = 2,
    kPlatformFieldNumber = 3,
  };
  // string bundle_id = 1 [json_name = "bundleId"];
  void clear_bundle_id() ;
  const ::std::string& bundle_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_bundle_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_bundle_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_bundle_id();
  void set_allocated_bundle_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_bundle_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_bundle_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_bundle_id();

  public:
  // string app_version = 2 [json_name = "appVersion"];
  void clear_app_version() ;
  const ::std::string& app_version() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_app_version(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_app_version();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_app_version();
  void set_allocated_app_version(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_app_version() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_app_version(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_app_version();

  public:
  // .proto.renderprotocol.api.v1.RPPlatform platform = 3 [json_name = "platform"];
  void clear_platform() ;
  ::proto::renderprotocol::api::v1::RPPlatform platform() const;
  void set_platform(::proto::renderprotocol::api::v1::RPPlatform value);

  private:
  ::proto::renderprotocol::api::v1::RPPlatform _internal_platform() const;
  void _internal_set_platform(::proto::renderprotocol::api::v1::RPPlatform value);

  public:
  // @@protoc_insertion_point(class_scope:proto.renderprotocol.api.v1.RPAppMetadata)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 70,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RPAppMetadata& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr bundle_id_;
    ::google::protobuf::internal::ArenaStringPtr app_version_;
    int platform_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5fmetadata_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RPAppMetadata_class_data_;
// -------------------------------------------------------------------

class RPApiMetadata final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.renderprotocol.api.v1.RPApiMetadata) */ {
 public:
  inline RPApiMetadata() : RPApiMetadata(nullptr) {}
  ~RPApiMetadata() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RPApiMetadata* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RPApiMetadata));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RPApiMetadata(::google::protobuf::internal::ConstantInitialized);

  inline RPApiMetadata(const RPApiMetadata& from) : RPApiMetadata(nullptr, from) {}
  inline RPApiMetadata(RPApiMetadata&& from) noexcept
      : RPApiMetadata(nullptr, ::std::move(from)) {}
  inline RPApiMetadata& operator=(const RPApiMetadata& from) {
    CopyFrom(from);
    return *this;
  }
  inline RPApiMetadata& operator=(RPApiMetadata&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RPApiMetadata& default_instance() {
    return *reinterpret_cast<const RPApiMetadata*>(
        &_RPApiMetadata_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(RPApiMetadata& a, RPApiMetadata& b) { a.Swap(&b); }
  inline void Swap(RPApiMetadata* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RPApiMetadata* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RPApiMetadata* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RPApiMetadata>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RPApiMetadata& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RPApiMetadata& from) { RPApiMetadata::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RPApiMetadata* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.renderprotocol.api.v1.RPApiMetadata"; }

  explicit RPApiMetadata(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RPApiMetadata(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RPApiMetadata& from);
  RPApiMetadata(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RPApiMetadata&& from) noexcept
      : RPApiMetadata(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAppMetadataFieldNumber = 1,
    kDeviceMetadataFieldNumber = 2,
  };
  // .proto.renderprotocol.api.v1.RPAppMetadata app_metadata = 1 [json_name = "appMetadata"];
  bool has_app_metadata() const;
  void clear_app_metadata() ;
  const ::proto::renderprotocol::api::v1::RPAppMetadata& app_metadata() const;
  [[nodiscard]] ::proto::renderprotocol::api::v1::RPAppMetadata* PROTOBUF_NULLABLE release_app_metadata();
  ::proto::renderprotocol::api::v1::RPAppMetadata* PROTOBUF_NONNULL mutable_app_metadata();
  void set_allocated_app_metadata(::proto::renderprotocol::api::v1::RPAppMetadata* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_app_metadata(::proto::renderprotocol::api::v1::RPAppMetadata* PROTOBUF_NULLABLE value);
  ::proto::renderprotocol::api::v1::RPAppMetadata* PROTOBUF_NULLABLE unsafe_arena_release_app_metadata();

  private:
  const ::proto::renderprotocol::api::v1::RPAppMetadata& _internal_app_metadata() const;
  ::proto::renderprotocol::api::v1::RPAppMetadata* PROTOBUF_NONNULL _internal_mutable_app_metadata();

  public:
  // .proto.renderprotocol.api.v1.RPDeviceMetadata device_metadata = 2 [json_name = "deviceMetadata"];
  bool has_device_metadata() const;
  void clear_device_metadata() ;
  const ::proto::renderprotocol::api::v1::RPDeviceMetadata& device_metadata() const;
  [[nodiscard]] ::proto::renderprotocol::api::v1::RPDeviceMetadata* PROTOBUF_NULLABLE release_device_metadata();
  ::proto::renderprotocol::api::v1::RPDeviceMetadata* PROTOBUF_NONNULL mutable_device_metadata();
  void set_allocated_device_metadata(::proto::renderprotocol::api::v1::RPDeviceMetadata* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_device_metadata(::proto::renderprotocol::api::v1::RPDeviceMetadata* PROTOBUF_NULLABLE value);
  ::proto::renderprotocol::api::v1::RPDeviceMetadata* PROTOBUF_NULLABLE unsafe_arena_release_device_metadata();

  private:
  const ::proto::renderprotocol::api::v1::RPDeviceMetadata& _internal_device_metadata() const;
  ::proto::renderprotocol::api::v1::RPDeviceMetadata* PROTOBUF_NONNULL _internal_mutable_device_metadata();

  public:
  // @@protoc_insertion_point(class_scope:proto.renderprotocol.api.v1.RPApiMetadata)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RPApiMetadata& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::proto::renderprotocol::api::v1::RPAppMetadata* PROTOBUF_NULLABLE app_metadata_;
    ::proto::renderprotocol::api::v1::RPDeviceMetadata* PROTOBUF_NULLABLE device_metadata_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5fmetadata_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RPApiMetadata_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RPAppMetadata

// string bundle_id = 1 [json_name = "bundleId"];
inline void RPAppMetadata::clear_bundle_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bundle_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& RPAppMetadata::bundle_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.api.v1.RPAppMetadata.bundle_id)
  return _internal_bundle_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RPAppMetadata::set_bundle_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.bundle_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:proto.renderprotocol.api.v1.RPAppMetadata.bundle_id)
}
inline ::std::string* PROTOBUF_NONNULL RPAppMetadata::mutable_bundle_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_bundle_id();
  // @@protoc_insertion_point(field_mutable:proto.renderprotocol.api.v1.RPAppMetadata.bundle_id)
  return _s;
}
inline const ::std::string& RPAppMetadata::_internal_bundle_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bundle_id_.Get();
}
inline void RPAppMetadata::_internal_set_bundle_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bundle_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RPAppMetadata::_internal_mutable_bundle_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.bundle_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RPAppMetadata::release_bundle_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.renderprotocol.api.v1.RPAppMetadata.bundle_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.bundle_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.bundle_id_.Set("", GetArena());
  }
  return released;
}
inline void RPAppMetadata::set_allocated_bundle_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.bundle_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.bundle_id_.IsDefault()) {
    _impl_.bundle_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.renderprotocol.api.v1.RPAppMetadata.bundle_id)
}

// string app_version = 2 [json_name = "appVersion"];
inline void RPAppMetadata::clear_app_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.app_version_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& RPAppMetadata::app_version() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.api.v1.RPAppMetadata.app_version)
  return _internal_app_version();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RPAppMetadata::set_app_version(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.app_version_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:proto.renderprotocol.api.v1.RPAppMetadata.app_version)
}
inline ::std::string* PROTOBUF_NONNULL RPAppMetadata::mutable_app_version()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_app_version();
  // @@protoc_insertion_point(field_mutable:proto.renderprotocol.api.v1.RPAppMetadata.app_version)
  return _s;
}
inline const ::std::string& RPAppMetadata::_internal_app_version() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.app_version_.Get();
}
inline void RPAppMetadata::_internal_set_app_version(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.app_version_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RPAppMetadata::_internal_mutable_app_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.app_version_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RPAppMetadata::release_app_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.renderprotocol.api.v1.RPAppMetadata.app_version)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.app_version_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.app_version_.Set("", GetArena());
  }
  return released;
}
inline void RPAppMetadata::set_allocated_app_version(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.app_version_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.app_version_.IsDefault()) {
    _impl_.app_version_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.renderprotocol.api.v1.RPAppMetadata.app_version)
}

// .proto.renderprotocol.api.v1.RPPlatform platform = 3 [json_name = "platform"];
inline void RPAppMetadata::clear_platform() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.platform_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::proto::renderprotocol::api::v1::RPPlatform RPAppMetadata::platform() const {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.api.v1.RPAppMetadata.platform)
  return _internal_platform();
}
inline void RPAppMetadata::set_platform(::proto::renderprotocol::api::v1::RPPlatform value) {
  _internal_set_platform(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:proto.renderprotocol.api.v1.RPAppMetadata.platform)
}
inline ::proto::renderprotocol::api::v1::RPPlatform RPAppMetadata::_internal_platform() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::proto::renderprotocol::api::v1::RPPlatform>(_impl_.platform_);
}
inline void RPAppMetadata::_internal_set_platform(::proto::renderprotocol::api::v1::RPPlatform value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.platform_ = value;
}

// -------------------------------------------------------------------

// RPDeviceMetadata

// string device_model = 1 [json_name = "deviceModel"];
inline void RPDeviceMetadata::clear_device_model() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.device_model_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& RPDeviceMetadata::device_model() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.api.v1.RPDeviceMetadata.device_model)
  return _internal_device_model();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RPDeviceMetadata::set_device_model(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.device_model_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:proto.renderprotocol.api.v1.RPDeviceMetadata.device_model)
}
inline ::std::string* PROTOBUF_NONNULL RPDeviceMetadata::mutable_device_model()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_device_model();
  // @@protoc_insertion_point(field_mutable:proto.renderprotocol.api.v1.RPDeviceMetadata.device_model)
  return _s;
}
inline const ::std::string& RPDeviceMetadata::_internal_device_model() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.device_model_.Get();
}
inline void RPDeviceMetadata::_internal_set_device_model(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.device_model_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RPDeviceMetadata::_internal_mutable_device_model() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.device_model_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RPDeviceMetadata::release_device_model() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.renderprotocol.api.v1.RPDeviceMetadata.device_model)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.device_model_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.device_model_.Set("", GetArena());
  }
  return released;
}
inline void RPDeviceMetadata::set_allocated_device_model(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.device_model_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.device_model_.IsDefault()) {
    _impl_.device_model_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.renderprotocol.api.v1.RPDeviceMetadata.device_model)
}

// string os_version = 2 [json_name = "osVersion"];
inline void RPDeviceMetadata::clear_os_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.os_version_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& RPDeviceMetadata::os_version() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.api.v1.RPDeviceMetadata.os_version)
  return _internal_os_version();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RPDeviceMetadata::set_os_version(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.os_version_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:proto.renderprotocol.api.v1.RPDeviceMetadata.os_version)
}
inline ::std::string* PROTOBUF_NONNULL RPDeviceMetadata::mutable_os_version()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_os_version();
  // @@protoc_insertion_point(field_mutable:proto.renderprotocol.api.v1.RPDeviceMetadata.os_version)
  return _s;
}
inline const ::std::string& RPDeviceMetadata::_internal_os_version() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.os_version_.Get();
}
inline void RPDeviceMetadata::_internal_set_os_version(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.os_version_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RPDeviceMetadata::_internal_mutable_os_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.os_version_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RPDeviceMetadata::release_os_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.renderprotocol.api.v1.RPDeviceMetadata.os_version)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.os_version_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.os_version_.Set("", GetArena());
  }
  return released;
}
inline void RPDeviceMetadata::set_allocated_os_version(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.os_version_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.os_version_.IsDefault()) {
    _impl_.os_version_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.renderprotocol.api.v1.RPDeviceMetadata.os_version)
}

// .proto.renderprotocol.api.v1.RPPlatform platform = 3 [json_name = "platform"];
inline void RPDeviceMetadata::clear_platform() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.platform_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::proto::renderprotocol::api::v1::RPPlatform RPDeviceMetadata::platform() const {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.api.v1.RPDeviceMetadata.platform)
  return _internal_platform();
}
inline void RPDeviceMetadata::set_platform(::proto::renderprotocol::api::v1::RPPlatform value) {
  _internal_set_platform(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:proto.renderprotocol.api.v1.RPDeviceMetadata.platform)
}
inline ::proto::renderprotocol::api::v1::RPPlatform RPDeviceMetadata::_internal_platform() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::proto::renderprotocol::api::v1::RPPlatform>(_impl_.platform_);
}
inline void RPDeviceMetadata::_internal_set_platform(::proto::renderprotocol::api::v1::RPPlatform value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.platform_ = value;
}

// -------------------------------------------------------------------

// RPApiMetadata

// .proto.renderprotocol.api.v1.RPAppMetadata app_metadata = 1 [json_name = "appMetadata"];
inline bool RPApiMetadata::has_app_metadata() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.app_metadata_ != nullptr);
  return value;
}
inline void RPApiMetadata::clear_app_metadata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.app_metadata_ != nullptr) _impl_.app_metadata_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::proto::renderprotocol::api::v1::RPAppMetadata& RPApiMetadata::_internal_app_metadata() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::proto::renderprotocol::api::v1::RPAppMetadata* p = _impl_.app_metadata_;
  return p != nullptr ? *p : reinterpret_cast<const ::proto::renderprotocol::api::v1::RPAppMetadata&>(::proto::renderprotocol::api::v1::_RPAppMetadata_default_instance_);
}
inline const ::proto::renderprotocol::api::v1::RPAppMetadata& RPApiMetadata::app_metadata() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.api.v1.RPApiMetadata.app_metadata)
  return _internal_app_metadata();
}
inline void RPApiMetadata::unsafe_arena_set_allocated_app_metadata(
    ::proto::renderprotocol::api::v1::RPAppMetadata* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.app_metadata_);
  }
  _impl_.app_metadata_ = reinterpret_cast<::proto::renderprotocol::api::v1::RPAppMetadata*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.renderprotocol.api.v1.RPApiMetadata.app_metadata)
}
inline ::proto::renderprotocol::api::v1::RPAppMetadata* PROTOBUF_NULLABLE RPApiMetadata::release_app_metadata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::proto::renderprotocol::api::v1::RPAppMetadata* released = _impl_.app_metadata_;
  _impl_.app_metadata_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::proto::renderprotocol::api::v1::RPAppMetadata* PROTOBUF_NULLABLE RPApiMetadata::unsafe_arena_release_app_metadata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.renderprotocol.api.v1.RPApiMetadata.app_metadata)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::proto::renderprotocol::api::v1::RPAppMetadata* temp = _impl_.app_metadata_;
  _impl_.app_metadata_ = nullptr;
  return temp;
}
inline ::proto::renderprotocol::api::v1::RPAppMetadata* PROTOBUF_NONNULL RPApiMetadata::_internal_mutable_app_metadata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.app_metadata_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::proto::renderprotocol::api::v1::RPAppMetadata>(GetArena());
    _impl_.app_metadata_ = reinterpret_cast<::proto::renderprotocol::api::v1::RPAppMetadata*>(p);
  }
  return _impl_.app_metadata_;
}
inline ::proto::renderprotocol::api::v1::RPAppMetadata* PROTOBUF_NONNULL RPApiMetadata::mutable_app_metadata()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::proto::renderprotocol::api::v1::RPAppMetadata* _msg = _internal_mutable_app_metadata();
  // @@protoc_insertion_point(field_mutable:proto.renderprotocol.api.v1.RPApiMetadata.app_metadata)
  return _msg;
}
inline void RPApiMetadata::set_allocated_app_metadata(::proto::renderprotocol::api::v1::RPAppMetadata* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.app_metadata_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.app_metadata_ = reinterpret_cast<::proto::renderprotocol::api::v1::RPAppMetadata*>(value);
  // @@protoc_insertion_point(field_set_allocated:proto.renderprotocol.api.v1.RPApiMetadata.app_metadata)
}

// .proto.renderprotocol.api.v1.RPDeviceMetadata device_metadata = 2 [json_name = "deviceMetadata"];
inline bool RPApiMetadata::has_device_metadata() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.device_metadata_ != nullptr);
  return value;
}
inline void RPApiMetadata::clear_device_metadata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.device_metadata_ != nullptr) _impl_.device_metadata_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::proto::renderprotocol::api::v1::RPDeviceMetadata& RPApiMetadata::_internal_device_metadata() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::proto::renderprotocol::api::v1::RPDeviceMetadata* p = _impl_.device_metadata_;
  return p != nullptr ? *p : reinterpret_cast<const ::proto::renderprotocol::api::v1::RPDeviceMetadata&>(::proto::renderprotocol::api::v1::_RPDeviceMetadata_default_instance_);
}
inline const ::proto::renderprotocol::api::v1::RPDeviceMetadata& RPApiMetadata::device_metadata() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.api.v1.RPApiMetadata.device_metadata)
  return _internal_device_metadata();
}
inline void RPApiMetadata::unsafe_arena_set_allocated_device_metadata(
    ::proto::renderprotocol::api::v1::RPDeviceMetadata* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.device_metadata_);
  }
  _impl_.device_metadata_ = reinterpret_cast<::proto::renderprotocol::api::v1::RPDeviceMetadata*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.renderprotocol.api.v1.RPApiMetadata.device_metadata)
}
inline ::proto::renderprotocol::api::v1::RPDeviceMetadata* PROTOBUF_NULLABLE RPApiMetadata::release_device_metadata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::renderprotocol::api::v1::RPDeviceMetadata* released = _impl_.device_metadata_;
  _impl_.device_metadata_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::proto::renderprotocol::api::v1::RPDeviceMetadata* PROTOBUF_NULLABLE RPApiMetadata::unsafe_arena_release_device_metadata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.renderprotocol.api.v1.RPApiMetadata.device_metadata)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::renderprotocol::api::v1::RPDeviceMetadata* temp = _impl_.device_metadata_;
  _impl_.device_metadata_ = nullptr;
  return temp;
}
inline ::proto::renderprotocol::api::v1::RPDeviceMetadata* PROTOBUF_NONNULL RPApiMetadata::_internal_mutable_device_metadata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.device_metadata_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::proto::renderprotocol::api::v1::RPDeviceMetadata>(GetArena());
    _impl_.device_metadata_ = reinterpret_cast<::proto::renderprotocol::api::v1::RPDeviceMetadata*>(p);
  }
  return _impl_.device_metadata_;
}
inline ::proto::renderprotocol::api::v1::RPDeviceMetadata* PROTOBUF_NONNULL RPApiMetadata::mutable_device_metadata()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::renderprotocol::api::v1::RPDeviceMetadata* _msg = _internal_mutable_device_metadata();
  // @@protoc_insertion_point(field_mutable:proto.renderprotocol.api.v1.RPApiMetadata.device_metadata)
  return _msg;
}
inline void RPApiMetadata::set_allocated_device_metadata(::proto::renderprotocol::api::v1::RPDeviceMetadata* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.device_metadata_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.device_metadata_ = reinterpret_cast<::proto::renderprotocol::api::v1::RPDeviceMetadata*>(value);
  // @@protoc_insertion_point(field_set_allocated:proto.renderprotocol.api.v1.RPApiMetadata.device_metadata)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace api
}  // namespace renderprotocol
}  // namespace proto


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5fmetadata_2eproto_2epb_2eh
