// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/renderprotocol/api/v1/rp_api_health_service.proto

#include "proto/renderprotocol/api/v1/rp_api_health_service.pb.h"
#include "proto/renderprotocol/api/v1/rp_api_health_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace proto {
namespace renderprotocol {
namespace api {
namespace v1 {

static const char* RPHealthService_method_names[] = {
  "/proto.renderprotocol.api.v1.RPHealthService/RPHealthCheck",
};

std::unique_ptr< RPHealthService::Stub> RPHealthService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RPHealthService::Stub> stub(new RPHealthService::Stub(channel, options));
  return stub;
}

RPHealthService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RPHealthCheck_(RPHealthService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RPHealthService::Stub::RPHealthCheck(::grpc::ClientContext* context, const ::proto::renderprotocol::api::v1::RPHealthCheckRequest& request, ::proto::renderprotocol::api::v1::RPHealthCheckResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::proto::renderprotocol::api::v1::RPHealthCheckRequest, ::proto::renderprotocol::api::v1::RPHealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RPHealthCheck_, context, request, response);
}

void RPHealthService::Stub::async::RPHealthCheck(::grpc::ClientContext* context, const ::proto::renderprotocol::api::v1::RPHealthCheckRequest* request, ::proto::renderprotocol::api::v1::RPHealthCheckResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::proto::renderprotocol::api::v1::RPHealthCheckRequest, ::proto::renderprotocol::api::v1::RPHealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RPHealthCheck_, context, request, response, std::move(f));
}

void RPHealthService::Stub::async::RPHealthCheck(::grpc::ClientContext* context, const ::proto::renderprotocol::api::v1::RPHealthCheckRequest* request, ::proto::renderprotocol::api::v1::RPHealthCheckResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RPHealthCheck_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::proto::renderprotocol::api::v1::RPHealthCheckResponse>* RPHealthService::Stub::PrepareAsyncRPHealthCheckRaw(::grpc::ClientContext* context, const ::proto::renderprotocol::api::v1::RPHealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::proto::renderprotocol::api::v1::RPHealthCheckResponse, ::proto::renderprotocol::api::v1::RPHealthCheckRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RPHealthCheck_, context, request);
}

::grpc::ClientAsyncResponseReader< ::proto::renderprotocol::api::v1::RPHealthCheckResponse>* RPHealthService::Stub::AsyncRPHealthCheckRaw(::grpc::ClientContext* context, const ::proto::renderprotocol::api::v1::RPHealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRPHealthCheckRaw(context, request, cq);
  result->StartCall();
  return result;
}

RPHealthService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RPHealthService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RPHealthService::Service, ::proto::renderprotocol::api::v1::RPHealthCheckRequest, ::proto::renderprotocol::api::v1::RPHealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RPHealthService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::proto::renderprotocol::api::v1::RPHealthCheckRequest* req,
             ::proto::renderprotocol::api::v1::RPHealthCheckResponse* resp) {
               return service->RPHealthCheck(ctx, req, resp);
             }, this)));
}

RPHealthService::Service::~Service() {
}

::grpc::Status RPHealthService::Service::RPHealthCheck(::grpc::ServerContext* context, const ::proto::renderprotocol::api::v1::RPHealthCheckRequest* request, ::proto::renderprotocol::api::v1::RPHealthCheckResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace proto
}  // namespace renderprotocol
}  // namespace api
}  // namespace v1
#include <grpcpp/ports_undef.inc>

