// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/renderprotocol/api/v1/rp_api_render_service.proto
// Protobuf C++ Version: 6.33.5

#ifndef proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5frender_5fservice_2eproto_2epb_2eh
#define proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5frender_5fservice_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "proto/renderprotocol/ui/v1/rp_ui_core.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5frender_5fservice_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5frender_5fservice_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5frender_5fservice_2eproto;
}  // extern "C"
namespace proto {
namespace renderprotocol {
namespace api {
namespace v1 {
class RPFetchRenderTreeRequest;
struct RPFetchRenderTreeRequestDefaultTypeInternal;
extern RPFetchRenderTreeRequestDefaultTypeInternal _RPFetchRenderTreeRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RPFetchRenderTreeRequest_class_data_;
class RPFetchRenderTreeResponse;
struct RPFetchRenderTreeResponseDefaultTypeInternal;
extern RPFetchRenderTreeResponseDefaultTypeInternal _RPFetchRenderTreeResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RPFetchRenderTreeResponse_class_data_;
}  // namespace v1
}  // namespace api
}  // namespace renderprotocol
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace proto {
namespace renderprotocol {
namespace api {
namespace v1 {

// ===================================================================


// -------------------------------------------------------------------

class RPFetchRenderTreeRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.renderprotocol.api.v1.RPFetchRenderTreeRequest) */ {
 public:
  inline RPFetchRenderTreeRequest() : RPFetchRenderTreeRequest(nullptr) {}
  ~RPFetchRenderTreeRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RPFetchRenderTreeRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RPFetchRenderTreeRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RPFetchRenderTreeRequest(::google::protobuf::internal::ConstantInitialized);

  inline RPFetchRenderTreeRequest(const RPFetchRenderTreeRequest& from) : RPFetchRenderTreeRequest(nullptr, from) {}
  inline RPFetchRenderTreeRequest(RPFetchRenderTreeRequest&& from) noexcept
      : RPFetchRenderTreeRequest(nullptr, ::std::move(from)) {}
  inline RPFetchRenderTreeRequest& operator=(const RPFetchRenderTreeRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline RPFetchRenderTreeRequest& operator=(RPFetchRenderTreeRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RPFetchRenderTreeRequest& default_instance() {
    return *reinterpret_cast<const RPFetchRenderTreeRequest*>(
        &_RPFetchRenderTreeRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(RPFetchRenderTreeRequest& a, RPFetchRenderTreeRequest& b) { a.Swap(&b); }
  inline void Swap(RPFetchRenderTreeRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RPFetchRenderTreeRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RPFetchRenderTreeRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RPFetchRenderTreeRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RPFetchRenderTreeRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RPFetchRenderTreeRequest& from) { RPFetchRenderTreeRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RPFetchRenderTreeRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.renderprotocol.api.v1.RPFetchRenderTreeRequest"; }

  explicit RPFetchRenderTreeRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RPFetchRenderTreeRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RPFetchRenderTreeRequest& from);
  RPFetchRenderTreeRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RPFetchRenderTreeRequest&& from) noexcept
      : RPFetchRenderTreeRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSessionTokenFieldNumber = 1,
    kViewIdFieldNumber = 2,
  };
  // string session_token = 1 [json_name = "sessionToken"];
  void clear_session_token() ;
  const ::std::string& session_token() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_session_token(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_session_token();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_session_token();
  void set_allocated_session_token(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_session_token() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_session_token(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_session_token();

  public:
  // string view_id = 2 [json_name = "viewId"];
  void clear_view_id() ;
  const ::std::string& view_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_view_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_view_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_view_id();
  void set_allocated_view_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_view_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_view_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_view_id();

  public:
  // @@protoc_insertion_point(class_scope:proto.renderprotocol.api.v1.RPFetchRenderTreeRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 81,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RPFetchRenderTreeRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr session_token_;
    ::google::protobuf::internal::ArenaStringPtr view_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5frender_5fservice_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RPFetchRenderTreeRequest_class_data_;
// -------------------------------------------------------------------

class RPFetchRenderTreeResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.renderprotocol.api.v1.RPFetchRenderTreeResponse) */ {
 public:
  inline RPFetchRenderTreeResponse() : RPFetchRenderTreeResponse(nullptr) {}
  ~RPFetchRenderTreeResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RPFetchRenderTreeResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RPFetchRenderTreeResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RPFetchRenderTreeResponse(::google::protobuf::internal::ConstantInitialized);

  inline RPFetchRenderTreeResponse(const RPFetchRenderTreeResponse& from) : RPFetchRenderTreeResponse(nullptr, from) {}
  inline RPFetchRenderTreeResponse(RPFetchRenderTreeResponse&& from) noexcept
      : RPFetchRenderTreeResponse(nullptr, ::std::move(from)) {}
  inline RPFetchRenderTreeResponse& operator=(const RPFetchRenderTreeResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline RPFetchRenderTreeResponse& operator=(RPFetchRenderTreeResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RPFetchRenderTreeResponse& default_instance() {
    return *reinterpret_cast<const RPFetchRenderTreeResponse*>(
        &_RPFetchRenderTreeResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(RPFetchRenderTreeResponse& a, RPFetchRenderTreeResponse& b) { a.Swap(&b); }
  inline void Swap(RPFetchRenderTreeResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RPFetchRenderTreeResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RPFetchRenderTreeResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RPFetchRenderTreeResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RPFetchRenderTreeResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RPFetchRenderTreeResponse& from) { RPFetchRenderTreeResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RPFetchRenderTreeResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.renderprotocol.api.v1.RPFetchRenderTreeResponse"; }

  explicit RPFetchRenderTreeResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RPFetchRenderTreeResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RPFetchRenderTreeResponse& from);
  RPFetchRenderTreeResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RPFetchRenderTreeResponse&& from) noexcept
      : RPFetchRenderTreeResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 1,
    kViewFieldNumber = 2,
  };
  // string id = 1 [json_name = "id"];
  void clear_id() ;
  const ::std::string& id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_id();
  void set_allocated_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_id();

  public:
  // .proto.renderprotocol.ui.v1.RPWidget view = 2 [json_name = "view"];
  bool has_view() const;
  void clear_view() ;
  const ::proto::renderprotocol::ui::v1::RPWidget& view() const;
  [[nodiscard]] ::proto::renderprotocol::ui::v1::RPWidget* PROTOBUF_NULLABLE release_view();
  ::proto::renderprotocol::ui::v1::RPWidget* PROTOBUF_NONNULL mutable_view();
  void set_allocated_view(::proto::renderprotocol::ui::v1::RPWidget* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_view(::proto::renderprotocol::ui::v1::RPWidget* PROTOBUF_NULLABLE value);
  ::proto::renderprotocol::ui::v1::RPWidget* PROTOBUF_NULLABLE unsafe_arena_release_view();

  private:
  const ::proto::renderprotocol::ui::v1::RPWidget& _internal_view() const;
  ::proto::renderprotocol::ui::v1::RPWidget* PROTOBUF_NONNULL _internal_mutable_view();

  public:
  // @@protoc_insertion_point(class_scope:proto.renderprotocol.api.v1.RPFetchRenderTreeResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 64,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RPFetchRenderTreeResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr id_;
    ::proto::renderprotocol::ui::v1::RPWidget* PROTOBUF_NULLABLE view_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5frender_5fservice_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RPFetchRenderTreeResponse_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RPFetchRenderTreeRequest

// string session_token = 1 [json_name = "sessionToken"];
inline void RPFetchRenderTreeRequest::clear_session_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_token_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& RPFetchRenderTreeRequest::session_token() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.api.v1.RPFetchRenderTreeRequest.session_token)
  return _internal_session_token();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RPFetchRenderTreeRequest::set_session_token(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.session_token_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:proto.renderprotocol.api.v1.RPFetchRenderTreeRequest.session_token)
}
inline ::std::string* PROTOBUF_NONNULL RPFetchRenderTreeRequest::mutable_session_token()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_session_token();
  // @@protoc_insertion_point(field_mutable:proto.renderprotocol.api.v1.RPFetchRenderTreeRequest.session_token)
  return _s;
}
inline const ::std::string& RPFetchRenderTreeRequest::_internal_session_token() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.session_token_.Get();
}
inline void RPFetchRenderTreeRequest::_internal_set_session_token(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_token_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RPFetchRenderTreeRequest::_internal_mutable_session_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.session_token_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RPFetchRenderTreeRequest::release_session_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.renderprotocol.api.v1.RPFetchRenderTreeRequest.session_token)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.session_token_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.session_token_.Set("", GetArena());
  }
  return released;
}
inline void RPFetchRenderTreeRequest::set_allocated_session_token(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.session_token_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.session_token_.IsDefault()) {
    _impl_.session_token_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.renderprotocol.api.v1.RPFetchRenderTreeRequest.session_token)
}

// string view_id = 2 [json_name = "viewId"];
inline void RPFetchRenderTreeRequest::clear_view_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.view_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& RPFetchRenderTreeRequest::view_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.api.v1.RPFetchRenderTreeRequest.view_id)
  return _internal_view_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RPFetchRenderTreeRequest::set_view_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.view_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:proto.renderprotocol.api.v1.RPFetchRenderTreeRequest.view_id)
}
inline ::std::string* PROTOBUF_NONNULL RPFetchRenderTreeRequest::mutable_view_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_view_id();
  // @@protoc_insertion_point(field_mutable:proto.renderprotocol.api.v1.RPFetchRenderTreeRequest.view_id)
  return _s;
}
inline const ::std::string& RPFetchRenderTreeRequest::_internal_view_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.view_id_.Get();
}
inline void RPFetchRenderTreeRequest::_internal_set_view_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.view_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RPFetchRenderTreeRequest::_internal_mutable_view_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.view_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RPFetchRenderTreeRequest::release_view_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.renderprotocol.api.v1.RPFetchRenderTreeRequest.view_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.view_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.view_id_.Set("", GetArena());
  }
  return released;
}
inline void RPFetchRenderTreeRequest::set_allocated_view_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.view_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.view_id_.IsDefault()) {
    _impl_.view_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.renderprotocol.api.v1.RPFetchRenderTreeRequest.view_id)
}

// -------------------------------------------------------------------

// RPFetchRenderTreeResponse

// string id = 1 [json_name = "id"];
inline void RPFetchRenderTreeResponse::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& RPFetchRenderTreeResponse::id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.api.v1.RPFetchRenderTreeResponse.id)
  return _internal_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RPFetchRenderTreeResponse::set_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:proto.renderprotocol.api.v1.RPFetchRenderTreeResponse.id)
}
inline ::std::string* PROTOBUF_NONNULL RPFetchRenderTreeResponse::mutable_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:proto.renderprotocol.api.v1.RPFetchRenderTreeResponse.id)
  return _s;
}
inline const ::std::string& RPFetchRenderTreeResponse::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_.Get();
}
inline void RPFetchRenderTreeResponse::_internal_set_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RPFetchRenderTreeResponse::_internal_mutable_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RPFetchRenderTreeResponse::release_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.renderprotocol.api.v1.RPFetchRenderTreeResponse.id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.id_.Set("", GetArena());
  }
  return released;
}
inline void RPFetchRenderTreeResponse::set_allocated_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.renderprotocol.api.v1.RPFetchRenderTreeResponse.id)
}

// .proto.renderprotocol.ui.v1.RPWidget view = 2 [json_name = "view"];
inline bool RPFetchRenderTreeResponse::has_view() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.view_ != nullptr);
  return value;
}
inline const ::proto::renderprotocol::ui::v1::RPWidget& RPFetchRenderTreeResponse::_internal_view() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::proto::renderprotocol::ui::v1::RPWidget* p = _impl_.view_;
  return p != nullptr ? *p : reinterpret_cast<const ::proto::renderprotocol::ui::v1::RPWidget&>(::proto::renderprotocol::ui::v1::_RPWidget_default_instance_);
}
inline const ::proto::renderprotocol::ui::v1::RPWidget& RPFetchRenderTreeResponse::view() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.renderprotocol.api.v1.RPFetchRenderTreeResponse.view)
  return _internal_view();
}
inline void RPFetchRenderTreeResponse::unsafe_arena_set_allocated_view(
    ::proto::renderprotocol::ui::v1::RPWidget* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.view_);
  }
  _impl_.view_ = reinterpret_cast<::proto::renderprotocol::ui::v1::RPWidget*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.renderprotocol.api.v1.RPFetchRenderTreeResponse.view)
}
inline ::proto::renderprotocol::ui::v1::RPWidget* PROTOBUF_NULLABLE RPFetchRenderTreeResponse::release_view() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::renderprotocol::ui::v1::RPWidget* released = _impl_.view_;
  _impl_.view_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::proto::renderprotocol::ui::v1::RPWidget* PROTOBUF_NULLABLE RPFetchRenderTreeResponse::unsafe_arena_release_view() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.renderprotocol.api.v1.RPFetchRenderTreeResponse.view)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::renderprotocol::ui::v1::RPWidget* temp = _impl_.view_;
  _impl_.view_ = nullptr;
  return temp;
}
inline ::proto::renderprotocol::ui::v1::RPWidget* PROTOBUF_NONNULL RPFetchRenderTreeResponse::_internal_mutable_view() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.view_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::proto::renderprotocol::ui::v1::RPWidget>(GetArena());
    _impl_.view_ = reinterpret_cast<::proto::renderprotocol::ui::v1::RPWidget*>(p);
  }
  return _impl_.view_;
}
inline ::proto::renderprotocol::ui::v1::RPWidget* PROTOBUF_NONNULL RPFetchRenderTreeResponse::mutable_view()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::renderprotocol::ui::v1::RPWidget* _msg = _internal_mutable_view();
  // @@protoc_insertion_point(field_mutable:proto.renderprotocol.api.v1.RPFetchRenderTreeResponse.view)
  return _msg;
}
inline void RPFetchRenderTreeResponse::set_allocated_view(::proto::renderprotocol::ui::v1::RPWidget* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.view_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.view_ = reinterpret_cast<::proto::renderprotocol::ui::v1::RPWidget*>(value);
  // @@protoc_insertion_point(field_set_allocated:proto.renderprotocol.api.v1.RPFetchRenderTreeResponse.view)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace api
}  // namespace renderprotocol
}  // namespace proto


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // proto_2frenderprotocol_2fapi_2fv1_2frp_5fapi_5frender_5fservice_2eproto_2epb_2eh
